In [1]:
import os
from pyspark.sql import SparkSession
from pyspark.sql.types import (
    DoubleType,
    IntegerType,
    StringType,
    StructField,
    StructType,
    TimestampType,
)

# 1. 스파크 세션 생성 (로컬 테스트용, 복잡한 외부 패키지 불필요)
spark = (
    SparkSession.builder.appName("ExtremeIngestionLocalTest")
    .master("local[*]")
    .config("spark.sql.adaptive.enabled", "true")  # AQE 활성화
    .config("spark.sql.adaptive.coalescePartitions.enabled", "true")
    .config("spark.sql.files.maxPartitionBytes", "134217728")  # 128MB 파티션
    .getOrCreate()
)

# 2. 테스트용 가짜 데이터(CSV)를 만들기 위한 경로 설정
local_dir = "./test_data"
os.makedirs(local_dir, exist_ok=True)
sample_csv_path = os.path.join(local_dir, "sample_logs.csv")

# 가상의 CSV 파일 생성 (실무에서는 이 위치에 수집할 파일들이 쌓임)
with open(sample_csv_path, "w", encoding="utf-8") as f:
    f.write("log_id,user_id,action_type,amount,event_time\n")
    f.write("LOG-001,101,click,15.5,2026-06-01 10:00:00\n")
    f.write("LOG-002,102,purchase,120.0,2026-06-01 11:30:00\n")
    f.write("LOG-003,101,view,5.0,2026-06-02 09:15:00\n")

# 3. [필수] 스키마 사전 정의 (inferSchema 차단으로 속도 극대화)
ingest_schema = StructType(
    [
        StructField("log_id", StringType(), False),
        StructField("user_id", IntegerType(), True),
        StructField("action_type", StringType(), True),
        StructField("amount", DoubleType(), True),
        StructField("event_time", TimestampType(), True),
    ]
)

# 4. [고성능 수집 단계]
df_raw = (
    spark.read.option("header", "true")
    .option("inferSchema", "false")  # 스키마 추론 생략 (병목 차단)
    .schema(ingest_schema)
    .csv(local_dir)
)

print("--- [수집된 원본 데이터 확인] ---")
df_raw.show()

# 5. [가공 및 적재 최적화]
# 날짜별 파티션을 위한 컬럼 생성
df_refined = df_raw.withColumn(
    "event_date", df_raw["event_time"].cast("date")
)

# 6. [최종 저장] Parquet 포맷 + 날짜별 파티셔닝 적용 적재
target_output_path = "./optimized_output_logs"

(
    df_refined.write.mode("overwrite")
    .partitionBy("event_date")
    .option("compression", "snappy")
    .parquet(target_output_path)
)

print(
    f"대용량 수집 및 최적화 Parquet 적재 완료! 저장 경로: {target_output_path}"
)

--- [수집된 원본 데이터 확인] ---
+-------+-------+-----------+------+-------------------+
| log_id|user_id|action_type|amount|         event_time|
+-------+-------+-----------+------+-------------------+
|LOG-001|    101|      click|  15.5|2026-06-01 10:00:00|
|LOG-002|    102|   purchase| 120.0|2026-06-01 11:30:00|
|LOG-003|    101|       view|   5.0|2026-06-02 09:15:00|
+-------+-------+-----------+------+-------------------+

대용량 수집 및 최적화 Parquet 적재 완료! 저장 경로: ./optimized_output_logs

In [5]:
import pandas as pd
import numpy as np
import time
import os

# 1. 2만 행의 데이터 생성
data = {
    'id': range(50000),
    'category': np.random.choice(['A', 'B', 'C', 'D'], 50000),
    'value': np.random.randn(50000),
    'timestamp': pd.date_range(start='2026-01-01', periods=50000, freq='min')
}
df = pd.DataFrame(data)

# 2. 성능 측정 준비
output_dir = "performance_test"
os.makedirs(output_dir, exist_ok=True)

# 3. CSV 저장 테스트
start_csv = time.time()
df.to_csv(os.path.join(output_dir, "test_data.csv"), index=False)
end_csv = time.time()
csv_duration = end_csv - start_csv
csv_size = os.path.getsize(os.path.join(output_dir, "test_data.csv"))

# 4. Parquet 저장 테스트
start_parquet = time.time()
df.to_parquet(os.path.join(output_dir, "test_data.parquet"), index=False, compression='snappy')
end_parquet = time.time()
parquet_duration = end_parquet - start_parquet
parquet_size = os.path.getsize(os.path.join(output_dir, "test_data.parquet"))

# 5. 결과 요약
results = {
    "Format": ["CSV", "Parquet"],
    "Time (seconds)": [csv_duration, parquet_duration],
    "File Size (bytes)": [csv_size, parquet_size]
}
results_df = pd.DataFrame(results)
print(results_df)

    Format  Time (seconds)  File Size (bytes)
0      CSV        0.094173            2370677
1  Parquet        0.018876            1217028

In [3]:
from bs4 import BeautifulSoup
import pandas as pd
import requests
from pyspark.sql import SparkSession

# 1. 스파크 세션 생성
spark = (
    SparkSession.builder.appName("MelonChartAnalysis")
    .master("local[*]")
    .config("spark.sql.adaptive.enabled", "true")
    .getOrCreate()
)

# 2. 멜론 TOP 100 크롤링 (Requests + BeautifulSoup)
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
}
url = "https://www.melon.com/chart/index.htm"
res = requests.get(url, headers=headers)
soup = BeautifulSoup(res.text, "html.parser")

rank_list, title_list, artist_list = [], [], []

# 50위까지, 100위까지의 태그 선택자 파싱
for item in soup.select("tbody > tr"):
    try:
        rank = item.select_one("span.rank").text
        title = item.select_one("div.rank01 a").text
        artist = item.select_one("div.rank02 a").text

        rank_list.append(int(rank))
        title_list.append(title)
        artist_list.append(artist)
    except AttributeError:
        continue

# 판다스 DataFrame 생성 후 스파크 DataFrame으로 변환
pd_df = pd.DataFrame(
    {"rank": rank_list, "title": title_list, "artist": artist_list}
)
df_melon = spark.createDataFrame(pd_df)

# [핵심 수집] 즉시 Parquet 포맷으로 압축 저장 (작은 파일 방지 및 메타데이터 확보)
df_melon.write.mode("overwrite").parquet("./melon_top100.parquet")
print("멜론 TOP 100 수집 및 Parquet 적재 완료!")

멜론 TOP 100 수집 및 Parquet 적재 완료!

In [19]:
from pyspark.sql import functions as F

# 1. 저장해 둔 파켓(Parquet) 파일 읽어오기 (컬럼 프로젝션과 메타데이터 즉시 로드)
df_melon = spark.read.parquet("./melon_top100.parquet")

print("--- [1. 수집된 데이터 확인] ---")
df_melon.show(10, truncate=False)

# -------------------------------------------------------------------------
# 2. 집계(Aggregation) 성능 최적화 예시: 아티스트별 곡 수 집계
# -------------------------------------------------------------------------
# 스파크는 셔플 전에 각 노드에서 미리 집계(Map-side Aggregation)를 수행합니다.
print("--- [2. 아티스트별 TOP 100 수록 곡 수 집계] ---")
artist_counts = (
    df_melon.groupBy("artist")
    .agg(
        F.count("title").alias("song_count"),
        F.min("rank").alias("highest_rank"),  # 가장 높은 순위
    )
    .orderBy(F.desc("song_count"), F.asc("highest_rank"))
)

artist_counts.show(20)

# -------------------------------------------------------------------------
# 3. 조인(Join) 성능 극대화 예시: 브로드캐스트 조인(Broadcast Join) 활용
# -------------------------------------------------------------------------
# 만약 가상의 '기획사(Agency)' 정보가 담긴 작은 데이터프레임이 있다고 가정해 봅시다.
agency_data = [
    ("aespa", "SM Entertainment"),
    ("IVE (아이브)", "Starship Entertainment"),
    ("RESCENE (리센느)", "더뮤즈 엔터테인먼트"),
    # ... (실무에서는 이 테이블이 수십만 건 이상일 수 있음)
]
df_agency = spark.createDataFrame(agency_data, ["artist", "agency"])

df_melon_clean = df_melon.withColumn(
    "artist", F.trim(F.col("artist"))
)  # 앞뒤 공백 제거

# [핵심] 작은 테이블은 broadcast() 함수로 감싸주어 네트워크 셔플을 원천 차단합니다.
print("--- [3. 브로드캐스트 조인을 통한 기획사 매핑] ---")
df_joined = df_melon_clean.join(
    F.broadcast(df_agency), on="artist", how="left"  # 작은 테이블 브로드캐스트 강제
)

df_joined.select("rank", "title", "artist", "agency").show(30, truncate=False)

# 곡의 개수 집계까지는 완벽하나
# 브로드캐스트 조인에서 다소 아쉬운 결과가 나왔다

--- [1. 수집된 데이터 확인] ---
+----+-----------+------------------+
|rank|title      |artist            |
+----+-----------+------------------+
|1   |BiiiG      |BIGBANG (빅뱅)    |
|2   |LOVE ATTACK|RESCENE (리센느)  |
|3   |갑자기     |아이오아이 (I.O.I)|
|4   |REDRED     |CORTIS (코르티스) |
|5   |Pretty Girl|RESCENE (리센느)  |
|6   |LEMONADE   |aespa             |
|7   |Deja Vu    |RESCENE (리센느)  |
|8   |만찬가     |태연 (TAEYEON)    |
|9   |It′s Me    |아일릿(ILLIT)     |
|10  |BAD        |ATEEZ(에이티즈)   |
+----+-----------+------------------+
only showing top 10 rows

--- [2. 아티스트별 TOP 100 수록 곡 수 집계] ---
+----------------------+----------+------------+
|                artist|song_count|highest_rank|
+----------------------+----------+------------+
|            방탄소년단|         6|          41|
|      RESCENE (리센느)|         4|           2|
|Hearts2Hearts (하츠...|         4|          16|
|       DAY6 (데이식스)|         4|          23|
|          IVE (아이브)|         4|          30|
|                 aespa|         3|           6|
|                한로로|         3|          14|
|           AKMU (악뮤)|         3|          15|
|                임영웅|         3|          40|
|                이무진|         3|          51|
|         아일릿(ILLIT)|         2|           9|
|       KiiiKiii (키키)|         2|          24|
|                 NMIXX|         2|          31|
|         제니 (JENNIE)|         2|          35|
|                로이킴|         2|          42|
|           로제 (ROSÉ)|         2|          48|
|          TWS (투어스)|         2|          60|
|        ALLDAY PROJECT|         2|          87|
|LE SSERAFIM (르세라핌)|         2|          89|
|        BIGBANG (빅뱅)|         1|           1|
+----------------------+----------+------------+
only showing top 20 rows

--- [3. 브로드캐스트 조인을 통한 기획사 매핑] ---
+----+--------------------------------------------+--------------------------+----------------+
|rank|title                                       |artist                    |agency          |
+----+--------------------------------------------+--------------------------+----------------+
|1   |BiiiG                                       |BIGBANG (빅뱅)            |NULL            |
|2   |LOVE ATTACK                                 |RESCENE (리센느)          |NULL            |
|3   |갑자기                                      |아이오아이 (I.O.I)        |NULL            |
|4   |REDRED                                      |CORTIS (코르티스)         |NULL            |
|5   |Pretty Girl                                 |RESCENE (리센느)          |NULL            |
|6   |LEMONADE                                    |aespa                     |SM Entertainment|
|7   |Deja Vu                                     |RESCENE (리센느)          |NULL            |
|8   |만찬가                                      |태연 (TAEYEON)            |NULL            |
|9   |It′s Me                                     |아일릿(ILLIT)             |NULL            |
|10  |BAD                                         |ATEEZ(에이티즈)           |NULL            |
|11  |여름아 부탁해                               |볼빨간사춘기              |NULL            |
|12  |Drowning                                    |WOODZ                     |NULL            |
|13  |캐치 캐치                                   |YENA (최예나)             |NULL            |
|14  |사랑하게 될 거야                            |한로로                    |NULL            |
|15  |소문의 낙원                                 |AKMU (악뮤)               |NULL            |
|16  |RUDE!                                       |Hearts2Hearts (하츠투하츠)|NULL            |
|17  |Good Goodbye                                |화사 (HWASA)              |NULL            |
|18  |Lemon Tang                                  |Hearts2Hearts (하츠투하츠)|NULL            |
|19  |기쁨, 슬픔, 아름다운 마음                   |AKMU (악뮤)               |NULL            |
|20  |0+0                                         |한로로                    |NULL            |
|21  |생각을 멈추다 보면                          |최유리                    |NULL            |
|22  |타임캡슐                                    |다비치                    |NULL            |
|23  |한 페이지가 될 수 있게                      |DAY6 (데이식스)           |NULL            |
|24  |Pop Off Pop Off                             |KiiiKiii (키키)           |NULL            |
|25  |404 (New Era)                               |KiiiKiii (키키)           |NULL            |
|26  |Popcorn                                     |도경수(D.O.)              |NULL            |
|27  |HOME SWEET HOME (feat. 태양, 대성)          |G-DRAGON                  |NULL            |
|28  |어떻게 이별까지 사랑하겠어, 널 사랑하는 거지|AKMU (악뮤)               |NULL            |
|29  |Surfin' Boy                                 |Red Velvet (레드벨벳)     |NULL            |
|30  |BANG BANG                                   |IVE (아이브)              |NULL            |
+----+--------------------------------------------+--------------------------+----------------+
only showing top 30 rows

In [20]:
# 리센느와 아이브가 포함된 행만 필터링해서 원본 문자열 출력 (앞뒤로 |를 붙여 공백 확인)
df_melon.filter(
    F.col("artist").like("%RESCENE%") | F.col("artist").like("%IVE%")
).select(
    F.concat(F.lit("["), F.col("artist"), F.lit("]"))
).show(
    truncate=False
)

+--------------------+
|concat([, artist, ])|
+--------------------+
|[RESCENE (리센느)]  |
|[RESCENE (리센느)]  |
|[RESCENE (리센느)]  |
|[IVE (아이브)]      |
|[RESCENE (리센느)]  |
|[IVE (아이브)]      |
|[IVE (아이브)]      |
|[IVE (아이브)]      |
+--------------------+

In [21]:
# 예시: 멜론 아티스트 이름에서 대소문자 무시 및 정제 후 조인하기
# (만약 멜론에는 "RESCENE"으로만 나오고, agency_data에는 "RESCENE (리센느)"로 되어있다면 방향을 맞춰주어야 합니다.)

# 1. 멜론 데이터의 아티스트 이름을 대문자로 통일하고 공백 제거
df_melon_clean = df_melon.withColumn(
    "artist_key", F.upper(F.trim(F.col("artist")))
)

# 2. 기획사 데이터도 동일하게 키 값 생성
agency_data = [
    ("AESPA", "SM Entertainment"),
    ("IVE", "Starship Entertainment"),  # 괄호 제거하고 핵심 키워드만 입력
    ("RESCENE", "더뮤즈 엔터테인먼트"),
]
df_agency = spark.createDataFrame(agency_data, ["artist_key", "agency"])

# 3. 정제된 키(artist_key)를 기준으로 브로드캐스트 조인 수행
df_joined = df_melon_clean.join(
    F.broadcast(df_agency), on="artist_key", how="left"
)

# 결과 확인 (artist_key 대신 원래 artist를 보여주도록 선택)
df_joined.select(
    "rank", "title", F.col("artist").alias("original_artist"), "agency"
).filter(
    F.col("original_artist").like("%RESCENE%")
    | F.col("original_artist").like("%IVE%")
).show(
    30, truncate=False
)

# 여전히 브로드캐스트 조인에서 다소 아쉬운 결과가 나왔다
# 즉 특수 공백 문자의 가능성이 있다

+----+-----------+----------------+------+
|rank|title      |original_artist |agency|
+----+-----------+----------------+------+
|2   |LOVE ATTACK|RESCENE (리센느)|NULL  |
|5   |Pretty Girl|RESCENE (리센느)|NULL  |
|7   |Deja Vu    |RESCENE (리센느)|NULL  |
|30  |BANG BANG  |IVE (아이브)    |NULL  |
|52  |Runaway    |RESCENE (리센느)|NULL  |
|74  |REBEL HEART|IVE (아이브)    |NULL  |
|96  |I AM       |IVE (아이브)    |NULL  |
|100 |BLACKHOLE  |IVE (아이브)    |NULL  |
+----+-----------+----------------+------+

In [22]:
from pyspark.sql import functions as F

# 1. 멜론 데이터의 아티스트 이름에서 특수 공백 문자(\u00A0)나 보이지 않는 공백을 일반 공백으로 치환 후 앞뒤 공백 제거
df_melon_clean = df_melon.withColumn(
    "artist_cleaned", F.trim(F.regexp_replace(F.col("artist"), "[\u00A0\s]+", " "))
)

# 2. 기획사 데이터도 동일하게 괄호 앞의 특수 공백이나 형태를 맞춰서 정의
agency_data = [
    ("aespa", "SM Entertainment"),
    (
        "IVE (아이브)",
        "Starship Entertainment",
    ),  # 혹은 아래 정규식으로 괄호째 날려버려도 좋습니다.
    ("RESCENE (리센느)", "더뮤즈 엔터테인먼트"),
]

df_agency = spark.createDataFrame(agency_data, ["artist", "agency"])
df_agency_clean = df_agency.withColumn(
    "artist_cleaned", F.trim(F.regexp_replace(F.col("artist"), "[\u00A0\s]+", " "))
)

# 3. 정제된 키('artist_cleaned')를 기준으로 브로드캐스트 조인 수행
print("--- [브로드캐스트 조인 재시도] ---")
df_joined = df_melon_clean.join(
    F.broadcast(df_agency_clean.select("artist_cleaned", "agency")),
    on="artist_cleaned",
    how="left",
)

# 결과 확인 (원래 아티스트 이름과 매핑된 기획사 확인)
df_joined.select(
    "rank", "title", F.col("artist").alias("original_artist"), "agency"
).filter(
    F.col("original_artist").like("%RESCENE%")
    | F.col("original_artist").like("%IVE%")
).show(
    30, truncate=False
)

--- [브로드캐스트 조인 재시도] ---
+----+-----------+----------------+----------------------+
|rank|title      |original_artist |agency                |
+----+-----------+----------------+----------------------+
|2   |LOVE ATTACK|RESCENE (리센느)|더뮤즈 엔터테인먼트   |
|5   |Pretty Girl|RESCENE (리센느)|더뮤즈 엔터테인먼트   |
|7   |Deja Vu    |RESCENE (리센느)|더뮤즈 엔터테인먼트   |
|30  |BANG BANG  |IVE (아이브)    |Starship Entertainment|
|52  |Runaway    |RESCENE (리센느)|더뮤즈 엔터테인먼트   |
|74  |REBEL HEART|IVE (아이브)    |Starship Entertainment|
|96  |I AM       |IVE (아이브)    |Starship Entertainment|
|100 |BLACKHOLE  |IVE (아이브)    |Starship Entertainment|
+----+-----------+----------------+----------------------+

In [23]:
from pyspark.sql import functions as F

# 1. 기존에 정제해 둔 멜론 데이터프레임 활용 (앞서 만든 artist_cleaned 장착)
df_melon_clean = df_melon.withColumn(
    "artist_cleaned", F.trim(F.regexp_replace(F.col("artist"), "[\u00A0\s]+", " "))
)

# 2. [확장] 기획사 정보 + 멤버(Members) 정보가 포함된 마스터 데이터 정의
# 실무에서는 이런 데이터가 RDB나 S3의 작은 참조 테이블(Dimension Table)로 존재합니다.
extended_agency_data = [
    ("aespa", "SM Entertainment", "카리나,윈터,지젤,닝닝"),
    ("IVE (아이브)", "Starship Entertainment", "안유진,가을,레이,장원영,리즈,이서"),
    ("RESCENE (리센느)", "더뮤즈 엔터테인먼트", "원이,리브,미나미,제나,메이"),
]

df_master = spark.createDataFrame(
    extended_agency_data, ["artist", "agency", "members"]
)

# 마스터 데이터도 동일하게 공백 정제 키 생성
df_master_clean = df_master.withColumn(
    "artist_cleaned", F.trim(F.regexp_replace(F.col("artist"), "[\u00A0\s]+", " "))
)

# 3. [핵심] 브로드캐스트 조인 수행 (참조 테이블이 작으므로 네트워크 셔플 제로!)
df_fully_joined = df_melon_clean.join(
    F.broadcast(df_master_clean.select("artist_cleaned", "agency", "members")),
    on="artist_cleaned",
    how="left",
)

# 4. 결과 출력 (순위, 제목, 아티스트, 기획사, 멤버 확인)
print("--- [멜론 TOP 100 + 기획사 + 멤버 브로드캐스트 조인 결과] ---")
df_fully_joined.select(
    "rank", 
    "title", 
    F.col("artist").alias("original_artist"), 
    "agency", 
    "members"
).filter(
    F.col("original_artist").like("%RESCENE%") | 
    F.col("original_artist").like("%IVE%") | 
    F.col("original_artist").like("%aespa%")
).show(30, truncate=False)

--- [멜론 TOP 100 + 기획사 + 멤버 브로드캐스트 조인 결과] ---
+----+---------------------------------------------+----------------+----------------------+---------------------------------+
|rank|title                                        |original_artist |agency                |members                          |
+----+---------------------------------------------+----------------+----------------------+---------------------------------+
|2   |LOVE ATTACK                                  |RESCENE (리센느)|더뮤즈 엔터테인먼트   |원이,리브,미나미,제나,메이       |
|5   |Pretty Girl                                  |RESCENE (리센느)|더뮤즈 엔터테인먼트   |원이,리브,미나미,제나,메이       |
|6   |LEMONADE                                     |aespa           |SM Entertainment      |카리나,윈터,지젤,닝닝            |
|7   |Deja Vu                                      |RESCENE (리센느)|더뮤즈 엔터테인먼트   |원이,리브,미나미,제나,메이       |
|30  |BANG BANG                                    |IVE (아이브)    |Starship Entertainment|안유진,가을,레이,장원영,리즈,이서|
|45  |Whiplash                                     |aespa           |SM Entertainment      |카리나,윈터,지젤,닝닝            |
|52  |Runaway                                      |RESCENE (리센느)|더뮤즈 엔터테인먼트   |원이,리브,미나미,제나,메이       |
|71  |WDA (Whole Different Animal) (Feat. G-DRAGON)|aespa           |SM Entertainment      |카리나,윈터,지젤,닝닝            |
|74  |REBEL HEART                                  |IVE (아이브)    |Starship Entertainment|안유진,가을,레이,장원영,리즈,이서|
|96  |I AM                                         |IVE (아이브)    |Starship Entertainment|안유진,가을,레이,장원영,리즈,이서|
|100 |BLACKHOLE                                    |IVE (아이브)    |Starship Entertainment|안유진,가을,레이,장원영,리즈,이서|
+----+---------------------------------------------+----------------+----------------------+---------------------------------+

In [26]:
from pyspark.sql import functions as F

# 1. 조인된 결과에서 아티스트 이름을 original_artist로 명확히 고정하여 DataFrame 새로 저장
df_fully_joined_named = df_fully_joined.withColumnRenamed("artist", "original_artist")

# 2. 멤버 문자열을 배열로 쪼갠 뒤 각각의 행으로 펼치기 (explode)
df_exploded = df_fully_joined_named.withColumn(
    "member_array", F.split(F.col("members"), ",")
).withColumn(
    "individual_member", F.explode(F.col("member_array"))
)

# 3. 결과 확인
df_exploded.select("title", "original_artist", "individual_member").show(20, truncate=False)

# individual_member (관계형 데이터베이스의 1NF(제1정규형) 형태인 원자값(Atomic Value) 구조로 바뀐 것)

+-----------+----------------+-----------------+
|title      |original_artist |individual_member|
+-----------+----------------+-----------------+
|LOVE ATTACK|RESCENE (리센느)|원이             |
|LOVE ATTACK|RESCENE (리센느)|리브             |
|LOVE ATTACK|RESCENE (리센느)|미나미           |
|LOVE ATTACK|RESCENE (리센느)|제나             |
|LOVE ATTACK|RESCENE (리센느)|메이             |
|Pretty Girl|RESCENE (리센느)|원이             |
|Pretty Girl|RESCENE (리센느)|리브             |
|Pretty Girl|RESCENE (리센느)|미나미           |
|Pretty Girl|RESCENE (리센느)|제나             |
|Pretty Girl|RESCENE (리센느)|메이             |
|LEMONADE   |aespa           |카리나           |
|LEMONADE   |aespa           |윈터             |
|LEMONADE   |aespa           |지젤             |
|LEMONADE   |aespa           |닝닝             |
|Deja Vu    |RESCENE (리센느)|원이             |
|Deja Vu    |RESCENE (리센느)|리브             |
|Deja Vu    |RESCENE (리센느)|미나미           |
|Deja Vu    |RESCENE (리센느)|제나             |
|Deja Vu    |RESCENE (리센느)|메이             |
|BANG BANG  |IVE (아이브)    |안유진           |
+-----------+----------------+-----------------+
only showing top 20 rows

In [31]:
# 캐싱 (Cache / Persist) — 중복 연산의 지옥 탈출하기
# 스파크는 기본적으로 지연 연산(Lazy Evaluation) 특성이 있어서, 
# 액션(show(), count(), write() 등)이 실행될 때마다 앞에서부터 연산을 다시 수행
# 따라서 반복해서 사용하는 데이터프레임은 메모리에 올려두어야(Cache) 합니다.

from pyspark.storagelevel import StorageLevel

# [핵심] 쪼개지고 조인된 완성형 데이터프레임을 메모리에 캐싱 선언
# - .cache()는 메모리 전용(MEMORY_AND_DISK 등 옵션 조절 가능)
df_exploded.cache()

# 첫 번째 액션 실행 (이 시점에 메모리에 적재됨)
print("--- [첫 번째 액션: 전체 멤버 분포 조회] ---")
df_exploded.groupBy("agency").count().show()

# 두 번째 액션 실행 (메모리에서 즉시 읽어오므로 속도가 비약적으로 빨라짐!)
print("--- [두 번째 액션: 특정 기획사 멤버들의 곡 조회] ---")
df_exploded.filter(F.col("agency") == "Starship Entertainment").select("title", "individual_member").show(25)

# 캐시를 다 사용한 후에는 메모리를 확보하기 위해 df_exploded.unpersist()

--- [첫 번째 액션: 전체 멤버 분포 조회] ---
+--------------------+-----+
|              agency|count|
+--------------------+-----+
|Starship Entertai...|   24|
| 더뮤즈 엔터테인먼트|   20|
|    SM Entertainment|   12|
+--------------------+-----+

--- [두 번째 액션: 특정 기획사 멤버들의 곡 조회] ---
+-----------+-----------------+
|      title|individual_member|
+-----------+-----------------+
|  BANG BANG|           안유진|
|  BANG BANG|             가을|
|  BANG BANG|             레이|
|  BANG BANG|           장원영|
|  BANG BANG|             리즈|
|  BANG BANG|             이서|
|REBEL HEART|           안유진|
|REBEL HEART|             가을|
|REBEL HEART|             레이|
|REBEL HEART|           장원영|
|REBEL HEART|             리즈|
|REBEL HEART|             이서|
|       I AM|           안유진|
|       I AM|             가을|
|       I AM|             레이|
|       I AM|           장원영|
|       I AM|             리즈|
|       I AM|             이서|
|  BLACKHOLE|           안유진|
|  BLACKHOLE|             가을|
|  BLACKHOLE|             레이|
|  BLACKHOLE|           장원영|
|  BLACKHOLE|             리즈|
|  BLACKHOLE|             이서|
+-----------+-----------------+

In [32]:
# 파티셔닝 (Partitioning) — 조회 성능의 극대화

# 자주 조회하는 조건(예: 기획사별, 날짜별)에 따라 물리적으로 폴더를 나누어 저장

# 조건에 맞는 폴더만 쏙 골라서 읽어옵니다

# [핵심] 'agency(기획사)' 기준으로 물리적 폴더를 나누어 Parquet로 저장
target_partition_path = "./melon_partitioned_data"

(
    df_exploded.write
    .mode("overwrite")
    .partitionBy("agency")  # 기획사별 폴더 파티셔닝
    .parquet(target_partition_path)
)

print("기획사별 파티셔닝 적재 완료!")

기획사별 파티셔닝 적재 완료!

In [33]:
# 파티셔닝된 경로에서 데이터 읽기
df_loaded = spark.read.parquet(target_partition_path)

# [Partition Pruning 발생] 
# 전체 테라바이트급 데이터 중 'Starship Entertainment' 폴더만 정확히 콕 집어서 읽음!
df_loaded.filter(F.col("agency") == "Starship Entertainment").select("title", "individual_member").show(truncate=False)

+-----------+-----------------+
|title      |individual_member|
+-----------+-----------------+
|REBEL HEART|안유진           |
|REBEL HEART|가을             |
|REBEL HEART|레이             |
|REBEL HEART|장원영           |
|REBEL HEART|리즈             |
|REBEL HEART|이서             |
|I AM       |안유진           |
|I AM       |가을             |
|I AM       |레이             |
|I AM       |장원영           |
|I AM       |리즈             |
|I AM       |이서             |
|BLACKHOLE  |안유진           |
|BLACKHOLE  |가을             |
|BLACKHOLE  |레이             |
|BLACKHOLE  |장원영           |
|BLACKHOLE  |리즈             |
|BLACKHOLE  |이서             |
|BANG BANG  |안유진           |
|BANG BANG  |가을             |
+-----------+-----------------+
only showing top 20 rows

In [34]:
# 🔥 요약: 스파크 성능을 극대화하는 최종 체크리스트

# 수집 단계: inferSchema 금지, 스키마 사전 정의 및 즉시 Parquet 변환 (I/O 감소)

# 조인 단계: 작은 테이블은 무조건 F.broadcast()로 셔플 원천 차단

# 구조화 단계: explode를 통한 정규화로 분산 처리 극대화

# 반복 연산 단계: 재사용되는 데이터는 .cache()로 메모리에 고정

# 저장 및 조회 단계: 자주 조회하는 컬럼 기준으로 partitionBy 적용 (Full Scan 방지)

In [50]:
# 이제 1차로 수집한 Top 100 결과를 parquet 에 저장하고

# 2차로 수집한 Topp 100 결과와 비교하여 순위 변화를 확인

# 멜론 TOP 100 크롤링 (Requests + BeautifulSoup)
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
}
url = "https://www.melon.com/chart/index.htm"
res = requests.get(url, headers=headers)
soup = BeautifulSoup(res.text, "html.parser")

rank_list, title_list, artist_list = [], [], []

# 50위까지, 100위까지의 태그 선택자 파싱
for item in soup.select("tbody > tr"):
    try:
        rank = item.select_one("span.rank").text
        title = item.select_one("div.rank01 a").text
        artist = item.select_one("div.rank02 a").text

        rank_list.append(int(rank))
        title_list.append(title)
        artist_list.append(artist)
    except AttributeError:
        continue

# 판다스 DataFrame 생성 후 스파크 DataFrame으로 변환
pd_df2 = pd.DataFrame(
    {"rank": rank_list, "title": title_list, "artist": artist_list}
)
df_melon2 = spark.createDataFrame(pd_df2)

# [핵심 수집] 즉시 Parquet 포맷으로 압축 저장 (작은 파일 방지 및 메타데이터 확보)
df_melon2.write.mode("overwrite").parquet("./melon_2차_top100.parquet")
print("멜론 TOP 100 수집 및 Parquet 적재 완료!")

멜론 TOP 100 수집 및 Parquet 적재 완료!

In [51]:
pd_df[27:]

    rank                      title                 artist
27    28  어떻게 이별까지 사랑하겠어, 널 사랑하는 거지              AKMU (악뮤)
28    29                Surfin' Boy      Red Velvet (레드벨벳)
29    30                  BANG BANG              IVE (아이브)
30    31             Heavy Serenade                  NMIXX
31    32                 어제보다 슬픈 오늘             우디 (Woody)
..   ...                        ...                    ...
95    96                       I AM              IVE (아이브)
96    97                        2.0                  방탄소년단
97    98                  OVERDRIVE              TWS (투어스)
98    99                      FOCUS  Hearts2Hearts (하츠투하츠)
99   100                  BLACKHOLE              IVE (아이브)

[73 rows x 3 columns]

In [52]:
pd_df2[27:]

    rank            title                 artist
27    28        BANG BANG              IVE (아이브)
28    29       어제보다 슬픈 오늘             우디 (Woody)
29    30   Heavy Serenade                  NMIXX
30    31         너의 모든 순간                    성시경
31    32  Pop Off Pop Off          KiiiKiii (키키)
..   ...              ...                    ...
95    96             I AM              IVE (아이브)
96    97            FOCUS  Hearts2Hearts (하츠투하츠)
97    98        BLACKHOLE              IVE (아이브)
98    99        OVERDRIVE              TWS (투어스)
99   100              2.0                  방탄소년단

[73 rows x 3 columns]

In [53]:
from pyspark.sql import functions as F
from pyspark.sql.window import Window

# 1. 1차(오전 10시)와 2차(오후 12시)에 저장해 둔 파켓 파일 각각 읽기
# (컬럼 프로젝션이 적용되어 필요한 메타데이터만 즉시 로드됩니다)
df_10am = spark.read.parquet("./melon_top100.parquet").withColumn(
    "time_slot", F.lit("10:00")
)

df_12pm = spark.read.parquet("./melon_2차_top100.parquet").withColumn(
    "time_slot", F.lit("12:00")
)

# 2. 두 데이터프레임을 위아래로 결합 (Union)
df_combined = df_10am.unionByName(df_12pm)

# 3. 10시 데이터와 12시 데이터를 곡 제목(title)과 아티스트(artist) 기준으로 나란히 배치
df_10 = df_combined.filter(F.col("time_slot") == "10:00").select(
    F.col("title"), F.col("artist"), F.col("rank").alias("rank_10am")
)

df_12 = df_combined.filter(F.col("time_slot") == "12:00").select(
    F.col("title"), F.col("artist"), F.col("rank").alias("rank_12pm")
)

# 4. 조인하여 순위 비교 (두 시간대에 공존하는 곡 기준, 혹은 left join으로 진입/이탈 곡 파악)
# 여기서는 10시와 12시 모두 비교하기 위해 outer join을 사용하거나 inner join을 사용할 수 있습니다.
df_rank_compare = df_10.join(
    df_12, on=["title", "artist"], how="outer"  # 새로 진입하거나 차트 아웃된 곡까지 모두 보려면 outer
)

# 5. 순위 변동 폭 계산
# (10시 순위 - 12시 순위: 양수면 순위 상승, 음수면 하락)
df_rank_diff = (
    df_rank_compare.withColumn(
        "rank_change", F.col("rank_10am") - F.col("rank_12pm")
    )
    .withColumn(
        "status",
        F.when(F.col("rank_10am").isNull(), "NEW 진입")
        .when(F.col("rank_12pm").isNull(), "OUT 아웃")
        .when(F.col("rank_change") > 0, "▲ 상승")
        .when(F.col("rank_change") < 0, "▼ 하락")
        .otherwise("- 유지"),
    )
)

print("--- [오전 10시 vs 오후 12시 멜론 차트 순위 변동 리포트] ---")
df_rank_diff.select(
    "title", "artist", "rank_10am", "rank_12pm", "rank_change", "status"
).orderBy(
    F.coalesce(F.col("rank_12pm"), F.lit(999))
).show(30, truncate=False)

--- [오전 10시 vs 오후 12시 멜론 차트 순위 변동 리포트] ---
+--------------------------------------------+--------------------------+---------+---------+-----------+------+
|title                                       |artist                    |rank_10am|rank_12pm|rank_change|status|
+--------------------------------------------+--------------------------+---------+---------+-----------+------+
|BiiiG                                       |BIGBANG (빅뱅)            |1        |1        |0          |- 유지|
|LOVE ATTACK                                 |RESCENE (리센느)          |2        |2        |0          |- 유지|
|갑자기                                      |아이오아이 (I.O.I)        |3        |3        |0          |- 유지|
|REDRED                                      |CORTIS (코르티스)         |4        |4        |0          |- 유지|
|Pretty Girl                                 |RESCENE (리센느)          |5        |5        |0          |- 유지|
|LEMONADE                                    |aespa                     |6        |6        |0          |- 유지|
|It′s Me                                     |아일릿(ILLIT)             |9        |7        |2          |▲ 상승|
|Deja Vu                                     |RESCENE (리센느)          |7        |8        |-1         |▼ 하락|
|만찬가                                      |태연 (TAEYEON)            |8        |9        |-1         |▼ 하락|
|BAD                                         |ATEEZ(에이티즈)           |10       |10       |0          |- 유지|
|여름아 부탁해                               |볼빨간사춘기              |11       |11       |0          |- 유지|
|Drowning                                    |WOODZ                     |12       |12       |0          |- 유지|
|캐치 캐치                                   |YENA (최예나)             |13       |13       |0          |- 유지|
|RUDE!                                       |Hearts2Hearts (하츠투하츠)|16       |14       |2          |▲ 상승|
|사랑하게 될 거야                            |한로로                    |14       |15       |-1         |▼ 하락|
|Good Goodbye                                |화사 (HWASA)              |17       |16       |1          |▲ 상승|
|소문의 낙원                                 |AKMU (악뮤)               |15       |17       |-2         |▼ 하락|
|기쁨, 슬픔, 아름다운 마음                   |AKMU (악뮤)               |19       |18       |1          |▲ 상승|
|0+0                                         |한로로                    |20       |19       |1          |▲ 상승|
|Lemon Tang                                  |Hearts2Hearts (하츠투하츠)|18       |20       |-2         |▼ 하락|
|타임캡슐                                    |다비치                    |22       |21       |1          |▲ 상승|
|한 페이지가 될 수 있게                      |DAY6 (데이식스)           |23       |22       |1          |▲ 상승|
|404 (New Era)                               |KiiiKiii (키키)           |25       |23       |2          |▲ 상승|
|HOME SWEET HOME (feat. 태양, 대성)          |G-DRAGON                  |27       |24       |3          |▲ 상승|
|생각을 멈추다 보면                          |최유리                    |21       |25       |-4         |▼ 하락|
|어떻게 이별까지 사랑하겠어, 널 사랑하는 거지|AKMU (악뮤)               |28       |26       |2          |▲ 상승|
|Popcorn                                     |도경수(D.O.)              |26       |27       |-1         |▼ 하락|
|BANG BANG                                   |IVE (아이브)              |30       |28       |2          |▲ 상승|
|어제보다 슬픈 오늘                          |우디 (Woody)              |32       |29       |3          |▲ 상승|
|Heavy Serenade                              |NMIXX                     |31       |30       |1          |▲ 상승|
+--------------------------------------------+--------------------------+---------+---------+-----------+------+
only showing top 30 rows

In [54]:
# 1. 1차(오전 10시) Parquet 파일 읽어서 확인
print("=== [1차 파일: ./melon_top100.parquet] ===")
df_10 = spark.read.parquet("./melon_top100.parquet")
print(f"총 데이터 건수: {df_10.count()}개")
df_10.orderBy("rank").show(10, truncate=False)

# 2. 2차(오후 12시) Parquet 파일 읽어서 확인
print("=== [2차 파일: ./melon_2차_top100.parquet] ===")
df_12 = spark.read.parquet("./melon_2차_top100.parquet")
print(f"총 데이터 건수: {df_12.count()}개")
df_12.orderBy("rank").show(10, truncate=False)

=== [1차 파일: ./melon_top100.parquet] ===
총 데이터 건수: 100개
+----+-----------+------------------+
|rank|title      |artist            |
+----+-----------+------------------+
|1   |BiiiG      |BIGBANG (빅뱅)    |
|2   |LOVE ATTACK|RESCENE (리센느)  |
|3   |갑자기     |아이오아이 (I.O.I)|
|4   |REDRED     |CORTIS (코르티스) |
|5   |Pretty Girl|RESCENE (리센느)  |
|6   |LEMONADE   |aespa             |
|7   |Deja Vu    |RESCENE (리센느)  |
|8   |만찬가     |태연 (TAEYEON)    |
|9   |It′s Me    |아일릿(ILLIT)     |
|10  |BAD        |ATEEZ(에이티즈)   |
+----+-----------+------------------+
only showing top 10 rows

=== [2차 파일: ./melon_2차_top100.parquet] ===
총 데이터 건수: 100개
+----+-----------+------------------+
|rank|title      |artist            |
+----+-----------+------------------+
|1   |BiiiG      |BIGBANG (빅뱅)    |
|2   |LOVE ATTACK|RESCENE (리센느)  |
|3   |갑자기     |아이오아이 (I.O.I)|
|4   |REDRED     |CORTIS (코르티스) |
|5   |Pretty Girl|RESCENE (리센느)  |
|6   |LEMONADE   |aespa             |
|7   |It′s Me    |아일릿(ILLIT)     |
|8   |Deja Vu    |RESCENE (리센느)  |
|9   |만찬가     |태연 (TAEYEON)    |
|10  |BAD        |ATEEZ(에이티즈)   |
+----+-----------+------------------+
only showing top 10 rows

In [56]:
# 멜론 TOP 100 크롤링 (Requests + BeautifulSoup)
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
}
url = "https://www.melon.com/chart/index.htm"
res = requests.get(url, headers=headers)
soup = BeautifulSoup(res.text, "html.parser")

rank_list, title_list, artist_list, album_list = [], [], [], []

# 50위까지, 100위까지의 태그 선택자 파싱
for item in soup.select("tbody > tr"):
    try:
        rank = item.select_one("span.rank").text
        title = item.select_one("div.rank01 a").text
        artist = item.select_one("div.rank02 a").text
        # [확장] 앨범명 태그 선택자 추가 (보통 div.rank03 a 에 위치함)
        album = item.select_one("div.rank03 a").text

        rank_list.append(int(rank))
        title_list.append(title)
        artist_list.append(artist)
        album_list.append(album)
    except AttributeError:
        continue

# 판다스 DataFrame 생성 (album_name 컬럼 추가)
pd_df3 = pd.DataFrame(
    {
        "rank": rank_list, 
        "title": title_list, 
        "artist": artist_list,
        "album_name": album_list
    }
)
df_melon3 = spark.createDataFrame(pd_df3)

In [58]:
pd_df3

,rank,title,artist,album_name
0,1,BiiiG,BIGBANG (빅뱅),BiiiG
1,2,LOVE ATTACK,RESCENE (리센느),SCENEDROME
2,3,갑자기,아이오아이 (I.O.I),I.O.I 3rd MINI ALBUM [I.O.I : LOOP]
3,4,REDRED,CORTIS (코르티스),GREENGREEN
4,5,Pretty Girl,RESCENE (리센느),Pretty Girl - Special Single
...,...,...,...,...
95,96,I AM,IVE (아이브),I've IVE
96,97,FOCUS,Hearts2Hearts (하츠투하츠),FOCUS - The 1st Mini Album
97,98,BLACKHOLE,IVE (아이브),REVIVE+
98,99,OVERDRIVE,TWS (투어스),play hard
99,100,2.0,방탄소년단,ARIRANG

In [59]:
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
}

# 1. 메인 차트 페이지 크롤링
url = "https://www.melon.com/chart/index.htm"
res = requests.get(url, headers=headers)
soup = BeautifulSoup(res.text, "html.parser")

rank_list, title_list, artist_list, album_list, date_list = [], [], [], [], []

print("멜론 TOP 100 메인 차트 파싱 및 상세 페이지(발매일) 수집 시작...")

for item in soup.select("tbody > tr"):
    try:
        # 곡 고유 ID 추출 (메인 테이블의 tr 태그 속성에 보통 data-song-no가 있음)
        song_id = item.get("data-song-no")
        rank = item.select_one("span.rank").text
        title = item.select_one("div.rank01 a").text
        artist = item.select_one("div.rank02 a").text
        album = item.select_one("div.rank03 a").text

        # 2. 각 곡의 상세 페이지에 접속하여 발매일(Release Date) 가져오기
        detail_url = f"https://www.melon.com/song/detail.htm?songId={song_id}"
        detail_res = requests.get(detail_url, headers=headers)
        detail_soup = BeautifulSoup(detail_res.text, "html.parser")

        # 멜론 상세 페이지의 발매일 영역 선택자 (meta 정보가 담긴 dl.list 또는 dd)
        # 보통 정보 영역에서 '발매일' 타이틀 다음의 텍스트를 파싱합니다.
        release_date = "정보 없음"
        meta_dl = detail_soup.select_one("div.section_info")
        if meta_dl:
            for dt in meta_dl.select("dt"):
                if "발매일" in dt.text:
                    # 바로 다음 형제 태그인 dd의 텍스트 가져오기
                    dd = dt.find_next_sibling("dd")
                    if dd:
                        release_date = dd.text.strip()
                        break

        # 리스트에 담기
        rank_list.append(int(rank))
        title_list.append(title)
        artist_list.append(artist)
        album_list.append(album)
        date_list.append(release_date)

        # 서버 차단 방지를 위한 미세한 딜레이 (0.1초)
        time.sleep(0.1)

    except Exception as e:
        # 에러가 난 곡은 건너뜀
        continue

# 3. 판다스 DataFrame으로 변환 후 스파크 DF로 적재
pd_df = pd.DataFrame({
    "rank": rank_list,
    "title": title_list,
    "artist": artist_list,
    "album_name": album_list,
    "release_date": date_list
})

df_melon_final = spark.createDataFrame(pd_df)

멜론 TOP 100 메인 차트 파싱 및 상세 페이지(발매일) 수집 시작...

In [60]:
pd_df

,rank,title,artist,album_name,release_date
0,1,BiiiG,BIGBANG (빅뱅),BiiiG,2026.08.19
1,2,LOVE ATTACK,RESCENE (리센느),SCENEDROME,2024.08.27
2,3,갑자기,아이오아이 (I.O.I),I.O.I 3rd MINI ALBUM [I.O.I : LOOP],2026.05.19
3,4,REDRED,CORTIS (코르티스),GREENGREEN,2026.04.20
4,5,Pretty Girl,RESCENE (리센느),Pretty Girl - Special Single,2026.07.08
...,...,...,...,...,...
95,96,I AM,IVE (아이브),I've IVE,2023.04.10
96,97,FOCUS,Hearts2Hearts (하츠투하츠),FOCUS - The 1st Mini Album,2025.10.20
97,98,BLACKHOLE,IVE (아이브),REVIVE+,2026.02.23
98,99,OVERDRIVE,TWS (투어스),play hard,2025.10.13
99,100,2.0,방탄소년단,ARIRANG,2026.03.20

In [63]:
# Parquet 파일로 저장
target_path = "./melon_2차_top100_with_date.parquet"
df_melon_final.write.mode("overwrite").parquet(target_path)

In [68]:
# 1. 저장된 파켓 파일 읽기 (또는 메모리에 있는 df_melon_final 그대로 사용)
df_melon_final = spark.read.parquet("./melon_2차_top100_with_date.parquet")

# 2. 데이터 건수 및 스키마 구조 확인
print(f"--- [데이터 총 건수: {df_melon_final.count()}개] ---")
df_melon_final.printSchema()

# 3. 상위 10개 데이터 조회 (순위, 제목, 가수, 앨범, 발매일)
print("--- [TOP 10 멜론 차트 & 상세 정보 리포트] ---")
df_melon_final.orderBy("rank").show(10, truncate=False)

--- [데이터 총 건수: 100개] ---
root
 |-- rank: long (nullable = true)
 |-- title: string (nullable = true)
 |-- artist: string (nullable = true)
 |-- album_name: string (nullable = true)
 |-- release_date: string (nullable = true)

--- [TOP 10 멜론 차트 & 상세 정보 리포트] ---
+----+-----------+------------------+-----------------------------------+------------+
|rank|title      |artist            |album_name                         |release_date|
+----+-----------+------------------+-----------------------------------+------------+
|1   |BiiiG      |BIGBANG (빅뱅)    |BiiiG                              |2026.08.19  |
|2   |LOVE ATTACK|RESCENE (리센느)  |SCENEDROME                         |2024.08.27  |
|3   |갑자기     |아이오아이 (I.O.I)|I.O.I 3rd MINI ALBUM [I.O.I : LOOP]|2026.05.19  |
|4   |REDRED     |CORTIS (코르티스) |GREENGREEN                         |2026.04.20  |
|5   |Pretty Girl|RESCENE (리센느)  |Pretty Girl - Special Single       |2026.07.08  |
|6   |LEMONADE   |aespa             |LEMONADE - The 2nd Album           |2026.05.29  |
|7   |It′s Me    |아일릿(ILLIT)     |MAMIHLAPINATAPAI                   |2026.04.30  |
|8   |Deja Vu    |RESCENE (리센느)  |Dearest                            |2025.07.02  |
|9   |만찬가     |태연 (TAEYEON)    |J-POP REMAKE Vol.1                 |2026.06.29  |
|10  |BAD        |ATEEZ(에이티즈)   |GOLDEN HOUR : Part.5               |2026.06.26  |
+----+-----------+------------------+-----------------------------------+------------+
only showing top 10 rows

In [69]:
from pyspark.sql import functions as F

# 1. '아이브' 또는 'IVE'가 포함된 아티스트 필터링
# (대소문자 무시 검색을 원하면 lower()를 쓸 수도 있지만, 보통 contains로 충분합니다)
df_ive = df_melon_final.filter(
    F.col("artist").contains("아이브") | F.col("artist").contains("IVE")
)

# 2. 결과 건수 확인
print(f"--- [아이브 차트 진입 곡 수: {df_ive.count()}개] ---")

# 3. 순위 순으로 정렬해서 리포트 출력
df_ive.orderBy("rank").show(truncate=False)

--- [아이브 차트 진입 곡 수: 4개] ---
+----+-----------+------------+-----------+------------+
|rank|title      |artist      |album_name |release_date|
+----+-----------+------------+-----------+------------+
|28  |BANG BANG  |IVE (아이브)|REVIVE+    |2026.02.09  |
|72  |REBEL HEART|IVE (아이브)|IVE EMPATHY|2025.01.13  |
|96  |I AM       |IVE (아이브)|I've IVE   |2023.04.10  |
|98  |BLACKHOLE  |IVE (아이브)|REVIVE+    |2026.02.23  |
+----+-----------+------------+-----------+------------+

In [7]:
import time
import requests
from bs4 import BeautifulSoup
import pandas as pd
from pyspark.sql import functions as F
from pyspark.sql import SparkSession

# 1. 스파크 세션 생성
spark = (
    SparkSession.builder.appName("MelonChartAnalysis")
    .master("local[*]")
    .config("spark.sql.adaptive.enabled", "true")
    .getOrCreate()
)

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
}

url = "https://www.melon.com/chart/index.htm"
res = requests.get(url, headers=headers)
soup = BeautifulSoup(res.text, "html.parser")

rank_list, title_list, artist_list, album_list, date_list, like_list, yesterday_rank_list = [], [], [], [], [], [], []

print("멜론 TOP 100 메인 및 상세 페이지 파싱 시작 (발매일, 좋아요, 어제 순위)...")

for item in soup.select("tbody > tr"):
    try:
        song_id = item.get("data-song-no")
        rank = item.select_one("span.rank").text
        title = item.select_one("div.rank01 a").text
        artist = item.select_one("div.rank02 a").text
        album = item.select_one("div.rank03 a").text

        # 상세 페이지 접속
        detail_url = f"https://www.melon.com/song/detail.htm?songId={song_id}"
        detail_res = requests.get(detail_url, headers=headers)
        detail_soup = BeautifulSoup(detail_res.text, "html.parser")

        # 1. 발매일 파싱 (<div class="meta"> 내부의 <dl class="list"> 탐색)
        release_date = "정보 없음"
        meta_dl = detail_soup.select_one("div.meta dl.list")
        if meta_dl:
            for dt, dd in zip(meta_dl.select("dt"), meta_dl.select("dd")):
                if "발매일" in dt.text:
                    release_date = dd.text.strip()
                    break

        # 2. 좋아요 수 파싱 (공백 및 줄바꿈 처리 추가)
        like_count = 0
        like_elem = detail_soup.select_one("#d_like_count")
        if like_elem:
            # 텍스트 내의 쉼표, 줄바꿈, 공백을 모두 제거
            like_text = like_elem.text.replace(",", "").replace("\n", "").strip()
            if like_text.isdigit():
                like_count = int(like_text)

        # 3. 어제의 차트 순위 파싱 (이미 성공함!)
        yesterday_rank = None  # 999 대신 None (NULL) 부여 (대신에 소수점 단위로 저장됨)
        chart_div = detail_soup.select_one("div.share div.chart")
        if chart_div:
            num_elem = chart_div.select_one("span.num")
            if num_elem and num_elem.text.strip().isdigit():
                yesterday_rank = int(num_elem.text.strip())

        # 데이터 리스트에 담기
        rank_list.append(int(rank))
        title_list.append(title)
        artist_list.append(artist)
        album_list.append(album)
        date_list.append(release_date)
        like_list.append(like_count)
        yesterday_rank_list.append(yesterday_rank)

        # 서버 부하 방지 딜레이
        time.sleep(0.1)

    except Exception as e:
        continue

# 판다스 DataFrame 생성 후 스파크 DF로 변환
pd_df = pd.DataFrame({
    "rank": rank_list,
    "title": title_list,
    "artist": artist_list,
    "album_name": album_list,
    "release_date": date_list,
    "likes": like_list,
    "yesterday_rank": yesterday_rank_list
})

df_melon_pro = spark.createDataFrame(pd_df)

# Parquet 파일로 저장
target_path = "./melon_pro_data.parquet"

# mode를 "overwrite"에서 "append"로 변경
# (만약 컬럼 순서나 미세한 스키마 차이가 걱정된다면 .option("mergeSchema", "true")를 함께 써주면 안전합니다)
df_melon_pro.write \
    .mode("append") \
    .option("mergeSchema", "true") \
    .parquet(target_path)

print("기존 데이터에 새로운 데이터 Append 적재 완료!")
df_melon_pro.orderBy("rank").show(10, truncate=False)

# 안타깝게도 좋아요 는 상세 페이지에서 확인이 불가능함

멜론 TOP 100 메인 및 상세 페이지 파싱 시작 (발매일, 좋아요, 어제 순위)...
기존 데이터에 새로운 데이터 Append 적재 완료!
+----+-----------+------------------+-----------------------------------+------------+-----+--------------+
|rank|title      |artist            |album_name                         |release_date|likes|yesterday_rank|
+----+-----------+------------------+-----------------------------------+------------+-----+--------------+
|1   |BiiiG      |BIGBANG (빅뱅)    |BiiiG                              |2026.08.19  |0    |NaN           |
|2   |LOVE ATTACK|RESCENE (리센느)  |SCENEDROME                         |2024.08.27  |0    |1.0           |
|3   |갑자기     |아이오아이 (I.O.I)|I.O.I 3rd MINI ALBUM [I.O.I : LOOP]|2026.05.19  |0    |2.0           |
|4   |REDRED     |CORTIS (코르티스) |GREENGREEN                         |2026.04.20  |0    |3.0           |
|5   |Pretty Girl|RESCENE (리센느)  |Pretty Girl - Special Single       |2026.07.08  |0    |5.0           |
|6   |LEMONADE   |aespa             |LEMONADE - The 2nd Album           |2026.05.29  |0    |4.0           |
|7   |Deja Vu    |RESCENE (리센느)  |Dearest                            |2025.07.02  |0    |7.0           |
|8   |It′s Me    |아일릿(ILLIT)     |MAMIHLAPINATAPAI                   |2026.04.30  |0    |6.0           |
|9   |만찬가     |태연 (TAEYEON)    |J-POP REMAKE Vol.1                 |2026.06.29  |0    |8.0           |
|10  |BAD        |ATEEZ(에이티즈)   |GOLDEN HOUR : Part.5               |2026.06.26  |0    |9.0           |
+----+-----------+------------------+-----------------------------------+------------+-----+--------------+
only showing top 10 rows

In [6]:
import requests
from bs4 import BeautifulSoup

# 테스트용 곡 ID (예: 방금 보신 BANG BANG의 ID)
test_song_id = "601237102"
detail_url = f"https://www.melon.com/song/detail.htm?songId={test_song_id}"

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
}

res = requests.get(detail_url, headers=headers)
soup = BeautifulSoup(res.text, "html.parser")

# 좋아요 요소 직접 찾기 테스트
like_elem = soup.select_one("#d_like_count")
if like_elem:
    print(f"찾은 좋아요 텍스트: [{like_elem.text}]")
else:
    print("❌ #d_like_count 태그를 아예 찾지 못했습니다!")

# 어제 순위 요소 직접 찾기 테스트
chart_div = soup.select_one("div.share div.chart")
if chart_div:
    print(f"찾은 어제 순위 HTML: [{chart_div}]")
else:
    print("❌ div.share div.chart 태그를 찾지 못했습니다!")

찾은 좋아요 텍스트: [
총건수
											0
										]
찾은 어제 순위 HTML: [<div class="chart">
<span class="bullet_icons chart_i"></span> 어제의 차트 순위 <span class="num">26</span>위
							</div>]

In [2]:
!pip install playwright
!playwright install chromium

Collecting playwright
  Downloading playwright-1.62.0-py3-none-manylinux1_x86_64.whl.metadata (3.3 kB)
Collecting pyee<14,>=13 (from playwright)
  Downloading pyee-13.0.1-py3-none-any.whl.metadata (3.0 kB)
Collecting greenlet<4.0.0,>=3.1.1 (from playwright)
  Downloading greenlet-3.5.5-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Requirement already satisfied: typing-extensions in /opt/conda/lib/python3.11/site-packages (from pyee<14,>=13->playwright) (4.8.0)
Downloading playwright-1.62.0-py3-none-manylinux1_x86_64.whl (47.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.7/47.7 MB 56.8 MB/s eta 0:00:00:00:0100:01
Downloading greenlet-3.5.5-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (624 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 624.6/624.6 kB 94.5 MB/s eta 0:00:00
Downloading pyee-13.0.1-py3-none-any.whl (15 kB)
Installing collected packages: pyee, greenlet, playwright
  Attempting uninstall: greenlet
    Found existing installation: greenlet 3.0.0
    Uninstalling greenlet-3.0.0:
      Successfully uninstalled greenlet-3.0.0
Successfully installed greenlet-3.5.5 playwright-1.62.0 pyee-13.0.1
Downloading Chrome for Testing 151.0.7922.34 (playwright chromium v1234) from https://cdn.playwright.dev/builds/cft/151.0.7922.34/linux64/chrome-linux64.zip
184.3 MiB [                    ] 0% 294.6s184.3 MiB [                    ] 0% 466.5s184.3 MiB [                    ] 0% 572.2s184.3 MiB [                    ] 0% 234.6s184.3 MiB [                    ] 0% 129.8s184.3 MiB [                    ] 0% 93.1s184.3 MiB [                    ] 0% 35.1s184.3 MiB [                    ] 2% 16.5s184.3 MiB [=                   ] 2% 12.6s184.3 MiB [=                   ] 3% 10.8s184.3 MiB [=                   ] 4% 10.8s184.3 MiB [=                   ] 4% 9.9s184.3 MiB [=                   ] 5% 9.0s184.3 MiB [=                   ] 6% 8.4s184.3 MiB [=                   ] 6% 8.9s184.3 MiB [=                   ] 6% 8.6s184.3 MiB [=                   ] 7% 8.1s184.3 MiB [==                  ] 7% 8.2s184.3 MiB [==                  ] 8% 7.8s184.3 MiB [==                  ] 8% 7.5s184.3 MiB [==                  ] 8% 7.8s184.3 MiB [==                  ] 9% 7.6s184.3 MiB [==                  ] 9% 7.4s184.3 MiB [==                  ] 10% 7.0s184.3 MiB [==                  ] 10% 7.1s184.3 MiB [==                  ] 11% 7.0s184.3 MiB [==                  ] 11% 6.8s184.3 MiB [==                  ] 12% 6.5s184.3 MiB [===                 ] 12% 6.3s184.3 MiB [===                 ] 12% 6.7s184.3 MiB [===                 ] 13% 6.5s184.3 MiB [===                 ] 13% 6.4s184.3 MiB [===                 ] 14% 6.2s184.3 MiB [===                 ] 15% 6.0s184.3 MiB [===                 ] 15% 6.3s184.3 MiB [===                 ] 15% 6.2s184.3 MiB [===                 ] 15% 6.0s184.3 MiB [===                 ] 16% 5.8s184.3 MiB [===                 ] 17% 6.0s184.3 MiB [====                ] 17% 5.8s184.3 MiB [====                ] 18% 5.8s184.3 MiB [====                ] 19% 5.7s184.3 MiB [====                ] 19% 5.6s184.3 MiB [====                ] 20% 5.6s184.3 MiB [====                ] 20% 5.4s184.3 MiB [====                ] 21% 5.2s184.3 MiB [====                ] 21% 5.4s184.3 MiB [====                ] 22% 5.3s184.3 MiB [=====               ] 22% 5.3s184.3 MiB [=====               ] 23% 5.1s184.3 MiB [=====               ] 23% 5.2s184.3 MiB [=====               ] 24% 5.1s184.3 MiB [=====               ] 24% 5.2s184.3 MiB [=====               ] 25% 5.0s184.3 MiB [=====               ] 25% 4.8s184.3 MiB [=====               ] 25% 5.0s184.3 MiB [=====               ] 26% 4.9s184.3 MiB [=====               ] 26% 5.0s184.3 MiB [======              ] 28% 4.8s184.3 MiB [======              ] 28% 4.7s184.3 MiB [======              ] 29% 4.7s184.3 MiB [======              ] 29% 4.6s184.3 MiB [======              ] 30% 4.6s184.3 MiB [======              ] 30% 4.5s184.3 MiB [======              ] 30% 4.6s184.3 MiB [======              ] 31% 4.5s184.3 MiB [======              ] 31% 4.4s184.3 MiB [======              ] 32% 4.4s184.3 MiB [=======             ] 32% 4.4s184.3 MiB [=======             ] 33% 4.3s184.3 MiB [=======             ] 34% 4.2s184.3 MiB [=======             ] 34% 4.3s184.3 MiB [=======             ] 34% 4.2s184.3 MiB [=======             ] 35% 4.2s184.3 MiB [=======             ] 35% 4.1s184.3 MiB [=======             ] 35% 4.2s184.3 MiB [=======             ] 36% 4.1s184.3 MiB [=======             ] 37% 4.0s184.3 MiB [========            ] 37% 4.0s184.3 MiB [========            ] 38% 3.9s184.3 MiB [========            ] 39% 3.9s184.3 MiB [========            ] 39% 3.8s184.3 MiB [========            ] 40% 3.8s184.3 MiB [========            ] 41% 3.8s184.3 MiB [========            ] 41% 3.7s184.3 MiB [========            ] 42% 3.7s184.3 MiB [=========           ] 42% 3.6s184.3 MiB [=========           ] 43% 3.6s184.3 MiB [=========           ] 44% 3.5s184.3 MiB [=========           ] 45% 3.5s184.3 MiB [=========           ] 45% 3.4s184.3 MiB [=========           ] 46% 3.4s184.3 MiB [=========           ] 47% 3.3s184.3 MiB [==========          ] 47% 3.3s184.3 MiB [==========          ] 48% 3.3s184.3 MiB [==========          ] 48% 3.2s184.3 MiB [==========          ] 49% 3.2s184.3 MiB [==========          ] 50% 3.1s184.3 MiB [==========          ] 51% 3.0s184.3 MiB [==========          ] 52% 3.0s184.3 MiB [===========         ] 52% 3.0s184.3 MiB [===========         ] 52% 2.9s184.3 MiB [===========         ] 53% 2.9s184.3 MiB [===========         ] 54% 2.9s184.3 MiB [===========         ] 54% 2.8s184.3 MiB [===========         ] 55% 2.8s184.3 MiB [===========         ] 55% 2.7s184.3 MiB [===========         ] 56% 2.7s184.3 MiB [===========         ] 57% 2.7s184.3 MiB [============        ] 57% 2.6s184.3 MiB [============        ] 58% 2.6s184.3 MiB [============        ] 59% 2.5s184.3 MiB [============        ] 60% 2.5s184.3 MiB [============        ] 60% 2.4s184.3 MiB [============        ] 61% 2.4s184.3 MiB [============        ] 62% 2.3s184.3 MiB [=============       ] 62% 2.3s184.3 MiB [=============       ] 63% 2.3s184.3 MiB [=============       ] 63% 2.2s184.3 MiB [=============       ] 64% 2.2s184.3 MiB [=============       ] 65% 2.1s184.3 MiB [=============       ] 66% 2.1s184.3 MiB [=============       ] 66% 2.0s184.3 MiB [=============       ] 67% 2.0s184.3 MiB [==============      ] 67% 2.0s184.3 MiB [==============      ] 69% 1.9s184.3 MiB [==============      ] 69% 1.8s184.3 MiB [==============      ] 70% 1.8s184.3 MiB [==============      ] 71% 1.8s184.3 MiB [==============      ] 71% 1.7s184.3 MiB [==============      ] 72% 1.7s184.3 MiB [===============     ] 72% 1.7s184.3 MiB [===============     ] 73% 1.6s184.3 MiB [===============     ] 74% 1.6s184.3 MiB [===============     ] 74% 1.5s184.3 MiB [===============     ] 75% 1.5s184.3 MiB [===============     ] 76% 1.5s184.3 MiB [===============     ] 76% 1.4s184.3 MiB [===============     ] 77% 1.4s184.3 MiB [================    ] 77% 1.4s184.3 MiB [================    ] 77% 1.3s184.3 MiB [================    ] 78% 1.3s184.3 MiB [================    ] 79% 1.3s184.3 MiB [================    ] 79% 1.2s184.3 MiB [================    ] 80% 1.2s184.3 MiB [================    ] 81% 1.1s184.3 MiB [================    ] 82% 1.1s184.3 MiB [=================   ] 82% 1.1s184.3 MiB [=================   ] 82% 1.0s184.3 MiB [=================   ] 83% 1.0s184.3 MiB [=================   ] 84% 1.0s184.3 MiB [=================   ] 84% 0.9s184.3 MiB [=================   ] 85% 0.9s184.3 MiB [=================   ] 85% 0.8s184.3 MiB [=================   ] 86% 0.8s184.3 MiB [=================   ] 87% 0.8s184.3 MiB [==================  ] 87% 0.7s184.3 MiB [==================  ] 88% 0.7s184.3 MiB [==================  ] 89% 0.6s184.3 MiB [==================  ] 90% 0.6s184.3 MiB [==================  ] 91% 0.5s184.3 MiB [==================  ] 92% 0.5s184.3 MiB [=================== ] 92% 0.4s184.3 MiB [=================== ] 93% 0.4s184.3 MiB [=================== ] 94% 0.4s184.3 MiB [=================== ] 94% 0.3s184.3 MiB [=================== ] 95% 0.3s184.3 MiB [=================== ] 95% 0.2s184.3 MiB [=================== ] 96% 0.2s184.3 MiB [=================== ] 97% 0.2s184.3 MiB [====================] 97% 0.1s184.3 MiB [====================] 98% 0.1s184.3 MiB [====================] 99% 0.0s184.3 MiB [====================] 100% 0.0s
Chrome for Testing 151.0.7922.34 (playwright chromium v1234) downloaded to /home/jovyan/.cache/ms-playwright/chromium-1234
Downloading FFmpeg (playwright ffmpeg v1011) from https://cdn.playwright.dev/dbazure/download/playwright/builds/ffmpeg/1011/ffmpeg-linux.zip
2.3 MiB [                    ] 0% 0.0s2.3 MiB [                    ] 2% 1.4s2.3 MiB [=                   ] 2% 3.4s2.3 MiB [=                   ] 3% 3.6s2.3 MiB [=                   ] 3% 3.5s2.3 MiB [=                   ] 4% 3.1s2.3 MiB [=                   ] 5% 3.0s2.3 MiB [=                   ] 6% 2.8s2.3 MiB [==                  ] 7% 2.7s2.3 MiB [==                  ] 8% 2.6s2.3 MiB [==                  ] 9% 2.5s2.3 MiB [==                  ] 9% 2.6s2.3 MiB [==                  ] 11% 2.3s2.3 MiB [===                 ] 12% 2.2s2.3 MiB [===                 ] 14% 2.1s2.3 MiB [===                 ] 15% 1.9s2.3 MiB [====                ] 17% 1.8s2.3 MiB [====                ] 20% 1.6s2.3 MiB [====                ] 21% 1.6s2.3 MiB [=====               ] 22% 1.5s2.3 MiB [=====               ] 25% 1.3s2.3 MiB [======              ] 27% 1.2s2.3 MiB [======              ] 30% 1.1s2.3 MiB [=======             ] 33% 1.0s2.3 MiB [=======             ] 36% 0.9s2.3 MiB [========            ] 40% 0.8s2.3 MiB [=========           ] 43% 0.7s2.3 MiB [=========           ] 46% 0.7s2.3 MiB [==========          ] 50% 0.6s2.3 MiB [===========         ] 55% 0.5s2.3 MiB [============        ] 60% 0.4s2.3 MiB [=============       ] 66% 0.3s2.3 MiB [==============      ] 72% 0.3s2.3 MiB [================    ] 78% 0.2s2.3 MiB [=================   ] 85% 0.1s2.3 MiB [==================  ] 90% 0.1s2.3 MiB [=================== ] 94% 0.0s2.3 MiB [====================] 98% 0.0s2.3 MiB [====================] 100% 0.0s
FFmpeg (playwright ffmpeg v1011) downloaded to /home/jovyan/.cache/ms-playwright/ffmpeg-1011
Downloading Chrome Headless Shell 151.0.7922.34 (playwright chromium-headless-shell v1234) from https://cdn.playwright.dev/builds/cft/151.0.7922.34/linux64/chrome-headless-shell-linux64.zip
114.7 MiB [                    ] 0% 0.0s114.7 MiB [                    ] 0% 299.9s114.7 MiB [                    ] 0% 305.1s114.7 MiB [                    ] 0% 144.1s114.7 MiB [                    ] 0% 54.0s114.7 MiB [                    ] 0% 35.6s114.7 MiB [                    ] 2% 15.3s114.7 MiB [=                   ] 3% 10.2s114.7 MiB [=                   ] 4% 9.1s114.7 MiB [=                   ] 4% 8.2s114.7 MiB [=                   ] 5% 7.2s114.7 MiB [=                   ] 6% 6.2s114.7 MiB [=                   ] 7% 6.6s114.7 MiB [==                  ] 7% 6.3s114.7 MiB [==                  ] 8% 5.9s114.7 MiB [==                  ] 9% 5.5s114.7 MiB [==                  ] 10% 5.1s114.7 MiB [==                  ] 10% 5.4s114.7 MiB [==                  ] 11% 5.0s114.7 MiB [===                 ] 12% 4.7s114.7 MiB [===                 ] 13% 4.7s114.7 MiB [===                 ] 14% 4.5s114.7 MiB [===                 ] 15% 4.4s114.7 MiB [===                 ] 16% 4.2s114.7 MiB [===                 ] 16% 4.1s114.7 MiB [===                 ] 17% 4.2s114.7 MiB [====                ] 18% 4.1s114.7 MiB [====                ] 18% 4.0s114.7 MiB [====                ] 19% 3.9s114.7 MiB [====                ] 20% 3.8s114.7 MiB [====                ] 21% 3.7s114.7 MiB [====                ] 21% 3.8s114.7 MiB [=====               ] 23% 3.5s114.7 MiB [=====               ] 24% 3.5s114.7 MiB [=====               ] 25% 3.5s114.7 MiB [=====               ] 26% 3.4s114.7 MiB [======              ] 27% 3.2s114.7 MiB [======              ] 27% 3.3s114.7 MiB [======              ] 28% 3.3s114.7 MiB [======              ] 28% 3.2s114.7 MiB [======              ] 29% 3.2s114.7 MiB [======              ] 30% 3.0s114.7 MiB [======              ] 31% 3.1s114.7 MiB [======              ] 31% 3.0s114.7 MiB [======              ] 32% 3.0s114.7 MiB [=======             ] 32% 2.9s114.7 MiB [=======             ] 33% 2.9s114.7 MiB [=======             ] 34% 2.8s114.7 MiB [=======             ] 35% 2.8s114.7 MiB [=======             ] 36% 2.7s114.7 MiB [=======             ] 37% 2.7s114.7 MiB [========            ] 38% 2.7s114.7 MiB [========            ] 38% 2.6s114.7 MiB [========            ] 39% 2.6s114.7 MiB [========            ] 41% 2.5s114.7 MiB [========            ] 42% 2.5s114.7 MiB [=========           ] 42% 2.4s114.7 MiB [=========           ] 43% 2.4s114.7 MiB [=========           ] 44% 2.4s114.7 MiB [=========           ] 45% 2.3s114.7 MiB [=========           ] 46% 2.2s114.7 MiB [=========           ] 47% 2.2s114.7 MiB [==========          ] 47% 2.1s114.7 MiB [==========          ] 48% 2.1s114.7 MiB [==========          ] 49% 2.1s114.7 MiB [==========          ] 50% 2.1s114.7 MiB [==========          ] 51% 2.0s114.7 MiB [==========          ] 52% 2.0s114.7 MiB [===========         ] 52% 2.0s114.7 MiB [===========         ] 52% 1.9s114.7 MiB [===========         ] 53% 1.9s114.7 MiB [===========         ] 54% 1.9s114.7 MiB [===========         ] 55% 1.8s114.7 MiB [===========         ] 56% 1.8s114.7 MiB [===========         ] 57% 1.7s114.7 MiB [============        ] 58% 1.7s114.7 MiB [============        ] 59% 1.7s114.7 MiB [============        ] 59% 1.6s114.7 MiB [============        ] 60% 1.6s114.7 MiB [============        ] 61% 1.6s114.7 MiB [============        ] 62% 1.5s114.7 MiB [=============       ] 62% 1.5s114.7 MiB [=============       ] 63% 1.5s114.7 MiB [=============       ] 64% 1.4s114.7 MiB [=============       ] 65% 1.4s114.7 MiB [=============       ] 66% 1.4s114.7 MiB [=============       ] 66% 1.3s114.7 MiB [=============       ] 67% 1.3s114.7 MiB [==============      ] 68% 1.3s114.7 MiB [==============      ] 68% 1.2s114.7 MiB [==============      ] 69% 1.2s114.7 MiB [==============      ] 70% 1.2s114.7 MiB [==============      ] 71% 1.1s114.7 MiB [===============     ] 72% 1.1s114.7 MiB [===============     ] 73% 1.1s114.7 MiB [===============     ] 73% 1.0s114.7 MiB [===============     ] 74% 1.0s114.7 MiB [===============     ] 75% 1.0s114.7 MiB [===============     ] 76% 0.9s114.7 MiB [===============     ] 77% 0.9s114.7 MiB [================    ] 78% 0.9s114.7 MiB [================    ] 78% 0.8s114.7 MiB [================    ] 79% 0.8s114.7 MiB [================    ] 80% 0.8s114.7 MiB [================    ] 81% 0.7s114.7 MiB [================    ] 82% 0.7s114.7 MiB [=================   ] 82% 0.7s114.7 MiB [=================   ] 83% 0.7s114.7 MiB [=================   ] 83% 0.6s114.7 MiB [=================   ] 84% 0.6s114.7 MiB [=================   ] 85% 0.6s114.7 MiB [=================   ] 86% 0.5s114.7 MiB [=================   ] 87% 0.5s114.7 MiB [==================  ] 87% 0.5s114.7 MiB [==================  ] 88% 0.5s114.7 MiB [==================  ] 88% 0.4s114.7 MiB [==================  ] 89% 0.4s114.7 MiB [==================  ] 90% 0.4s114.7 MiB [==================  ] 91% 0.3s114.7 MiB [==================  ] 92% 0.3s114.7 MiB [=================== ] 93% 0.3s114.7 MiB [=================== ] 93% 0.2s114.7 MiB [=================== ] 94% 0.2s114.7 MiB [=================== ] 95% 0.2s114.7 MiB [=================== ] 96% 0.1s114.7 MiB [=================== ] 97% 0.1s114.7 MiB [====================] 97% 0.1s114.7 MiB [====================] 98% 0.1s114.7 MiB [====================] 98% 0.0s114.7 MiB [====================] 99% 0.0s114.7 MiB [====================] 100% 0.0s
Chrome Headless Shell 151.0.7922.34 (playwright chromium-headless-shell v1234) downloaded to /home/jovyan/.cache/ms-playwright/chromium_headless_shell-1234

In [3]:
!playwright install-deps

# 설치를 위해 docker 를 관리자 권한으로 open 해야 함

# docker run -it --rm --user root -e GRANT_SUDO=yes  -p 8888:8888   -p 4040:4040   -v "$(pwd)/work:/home/jovyan/work"   jupyter/pyspark-notebook:latest

Installing dependencies...
Switching to root user to install dependencies...
Get:1 http://archive.ubuntu.com/ubuntu jammy InRelease [270 kB]
Get:2 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:4 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [84.1 kB]
Get:5 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,314 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:7 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [7,569 kB]
Get:8 http://archive.ubuntu.com/ubuntu jammy/multiverse amd64 Packages [266 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy/restricted amd64 Packages [164 kB]
Get:10 http://archive.ubuntu.com/ubuntu jammy/main amd64 Packages [1,792 kB]
Get:11 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [4,203 kB]
Get:12 http://archive.ubuntu.com/ubuntu jammy/universe amd64 Packages [17.5 MB]
Get:13 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [4,563 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [7,914 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,617 kB]
Get:16 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [92.7 kB]
Get:17 http://archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [35.6 kB]
Get:18 http://archive.ubuntu.com/ubuntu jammy-backports/main amd64 Packages [82.8 kB]
Fetched 47.8 MB in 4s (13.0 MB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
fonts-liberation is already the newest version (1:1.07.4-11).
libfontconfig1 is already the newest version (2.13.1-4.2ubuntu5).
libfontconfig1 set to manually installed.
libglx0 is already the newest version (1.4.0-1).
libglx0 set to manually installed.
libicu70 is already the newest version (70.1-2).
libicu70 set to manually installed.
libjpeg-turbo8 is already the newest version (2.1.2-0ubuntu1).
libjpeg-turbo8 set to manually installed.
libopus0 is already the newest version (1.3.1-0.1build2).
libopus0 set to manually installed.
libxcb-shm0 is already the newest version (1.14-3ubuntu3).
libxcb-shm0 set to manually installed.
libxcb1 is already the newest version (1.14-3ubuntu3).
libxcb1 set to manually installed.
libxcursor1 is already the newest version (1:1.2.0-2build4).
libxcursor1 set to manually installed.
libxext6 is already the newest version (2:1.3.4-1build1).
libxext6 set to manually installed.
libxfixes3 is already the newest version (1:6.0.0-1).
libxfixes3 set to manually installed.
libxi6 is already the newest version (2:1.8-1build1).
libxi6 set to manually installed.
libxkbcommon0 is already the newest version (1.4.0-1).
libxkbcommon0 set to manually installed.
libxrandr2 is already the newest version (2:1.5.2-1build1).
libxrandr2 set to manually installed.
libxrender1 is already the newest version (1:0.9.10-1build4).
libxrender1 set to manually installed.
libx264-163 is already the newest version (2:0.163.3060+git5db6aa6-2build1).
libx264-163 set to manually installed.
libdbus-1-3 is already the newest version (1.12.20-2ubuntu4.1).
libdbus-1-3 set to manually installed.
libdrm2 is already the newest version (2.4.113-2~ubuntu0.22.04.1).
libdrm2 set to manually installed.
libpango-1.0-0 is already the newest version (1.50.6+ds-2ubuntu1).
libpango-1.0-0 set to manually installed.
libpangocairo-1.0-0 is already the newest version (1.50.6+ds-2ubuntu1).
libpangocairo-1.0-0 set to manually installed.
libwayland-client0 is already the newest version (1.20.0-1ubuntu0.1).
libwayland-client0 set to manually installed.
libwayland-egl1 is already the newest version (1.20.0-1ubuntu0.1).
libwayland-egl1 set to manually installed.
libwayland-server0 is already the newest version (1.20.0-1ubuntu0.1).
libwayland-server0 set to manually installed.
libx11-6 is already the newest version (2:1.7.5-1ubuntu0.3).
libx11-6 set to manually installed.
libx11-xcb1 is already the newest version (2:1.7.5-1ubuntu0.3).
libx11-xcb1 set to manually installed.
ffmpeg is already the newest version (7:4.4.2-0ubuntu0.22.04.1).
The following additional packages will be installed:
  adwaita-icon-theme dbus dbus-user-session dconf-gsettings-backend
  dconf-service dictionaries-common emacsen-common gcc-12-base glib-networking
  glib-networking-common glib-networking-services gsettings-desktop-schemas
  gtk-update-icon-cache hicolor-icon-theme humanity-icon-theme hunspell-en-us
  iso-codes libaa1 libabsl20210324 libargon2-1 libasound2-data libaspell15
  libatk1.0-data libcairo-script-interpreter2 libcap2-bin libcc1-0
  libcdparanoia0 libcolord2 libcryptsetup12 libdca0 libdconf1 libde265-0
  libdevmapper1.02.1 libdv4 libdvdnav4 libdvdread8 libdw1 libegl-mesa0 libelf1
  libfaad2 libfluidsynth3 libfontenc1 libfreeaptx0 libgav1-0 libgcc-s1
  libgdk-pixbuf2.0-common libgfortran5 libgl1-mesa-dri libglapi-mesa
  libglx-mesa0 libgomp1 libgpm2 libgraphene-1.0-0 libgssdp-1.2-0
  libgstreamer-plugins-bad1.0-0 libgstreamer-plugins-good1.0-0 libgtk-3-common
  libgtk-4-common libgupnp-1.2-1 libgupnp-igd-1.0-4 libhunspell-1.7-0
  libilmbase25 libinstpatch-1.0-2 libip4tc2 libitm1 libjson-c5
  libjson-glib-1.0-0 libjson-glib-1.0-common libkate1 libkmod2 libldacbt-enc2
  liblsan0 libltc11 liblzo2-2 libmjpegutils-2.1-0 libmodplug1 libmpcdec6
  libmpeg2encpp-2.1-0 libmplex2-2.1-0 libnice10 libopenexr25 libopenh264-6
  libopenni2-0 liborc-0.4-0 libpam-systemd libqrencode4 libquadmath0 libsbc1
  libsecret-common libshout3 libsoundtouch1 libsoup-3.0-common libsoup2.4-1
  libsoup2.4-common libspandsp2 libsrtp2-1 libstdc++6 libsystemd0 libtag1v5
  libtag1v5-vanilla libtext-iconv-perl libubsan1 libunwind8 libv4l-0
  libv4lconvert0 libvisual-0.4-0 libvo-aacenc0 libvo-amrwbenc0 libwavpack1
  libwebrtc-audio-processing1 libwildmidi2 libxfont2 libxkbfile1 libxmuu1
  libyuv0 libzbar0 libzxingcore1 session-migration systemd systemd-sysv
  timgm6mb-soundfont ubuntu-mono x11-xkb-utils xauth xfonts-encodings
  xfonts-utils xserver-common
Suggested packages:
  ispell | aspell | hunspell wordlist frei0r-plugins gvfs hunspell
  openoffice.org-hunspell | openoffice.org-core isoquery libasound2-plugins
  alsa-utils aspell colord cups-common libdv-bin oss-compat libdvdcss2
  libenchant-2-voikko gpm libvisual-0.4-plugins gstreamer1.0-tools
  libgtk-4-media-gstreamer | libgtk-4-media-ffmpeg liblcms2-utils gnome-shell
  | notification-daemon libwildmidi-config systemd-container
  libtss2-esys-3.0.2-0 libtss2-mu0 libtss2-rc0 policykit-1 fluid-soundfont-gm
Recommended packages:
  librsvg2-common fonts-ipafont-mincho fonts-tlwg-loma gstreamer1.0-x
  alsa-ucm-conf alsa-topology-conf aspell-en | aspell-dictionary
  | aspell6a-dictionary at-spi2-core libpam-cap dmsetup enchant-2
  libgdk-pixbuf2.0-bin libgl1-amber-dri libglib2.0-data xdg-user-dirs
  gstreamer1.0-gl libgtk-3-bin libgtk-4-bin libmagickcore-6.q16-6-extra
  networkd-dispatcher systemd-timesyncd | time-daemon libnss-systemd
  xfonts-base
The following NEW packages will be installed:
  adwaita-icon-theme dbus dbus-user-session dconf-gsettings-backend
  dconf-service dictionaries-common emacsen-common fonts-freefont-ttf
  fonts-ipafont-gothic fonts-noto-color-emoji fonts-tlwg-loma-otf
  fonts-unifont fonts-wqy-zenhei glib-networking glib-networking-common
  glib-networking-services gsettings-desktop-schemas gstreamer1.0-libav
  gstreamer1.0-plugins-bad gstreamer1.0-plugins-base gstreamer1.0-plugins-good
  gtk-update-icon-cache hicolor-icon-theme humanity-icon-theme hunspell-en-us
  iso-codes libaa1 libabsl20210324 libargon2-1 libaspell15 libatk-bridge2.0-0
  libatk1.0-0 libatk1.0-data libatspi2.0-0 libavif13
  libcairo-script-interpreter2 libcap2-bin libcdparanoia0 libcolord2
  libcryptsetup12 libdbus-glib-1-2 libdca0 libdconf1 libde265-0
  libdevmapper1.02.1 libdv4 libdvdnav4 libdvdread8 libdw1 libegl-mesa0 libegl1
  libenchant-2-2 libepoxy0 libevdev2 libevent-2.1-7 libfaad2 libffi7
  libfluidsynth3 libfontenc1 libfreeaptx0 libgav1-0 libgles2 libgpm2
  libgraphene-1.0-0 libgssdp-1.2-0 libgstreamer-gl1.0-0
  libgstreamer-plugins-bad1.0-0 libgstreamer-plugins-base1.0-0
  libgstreamer-plugins-good1.0-0 libgstreamer1.0-0 libgtk-3-0 libgtk-3-common
  libgtk-4-1 libgtk-4-common libgudev-1.0-0 libgupnp-1.2-1 libgupnp-igd-1.0-4
  libharfbuzz-icu0 libhunspell-1.7-0 libhyphen0 libilmbase25
  libinstpatch-1.0-2 libip4tc2 libjson-c5 libjson-glib-1.0-0
  libjson-glib-1.0-common libkate1 libkmod2 libldacbt-enc2 libltc11 liblzo2-2
  libmanette-0.2-0 libmjpegutils-2.1-0 libmodplug1 libmpcdec6
  libmpeg2encpp-2.1-0 libmplex2-2.1-0 libnice10 libnotify4 libopenexr25
  libopengl0 libopenh264-6 libopenni2-0 liborc-0.4-0 libpam-systemd
  libproxy1v5 libqrencode4 libsbc1 libsecret-1-0 libsecret-common libshout3
  libsoundtouch1 libsoup-3.0-0 libsoup-3.0-common libsoup2.4-1
  libsoup2.4-common libspandsp2 libsrtp2-1 libtag1v5 libtag1v5-vanilla
  libtext-iconv-perl libunwind8 libv4l-0 libv4lconvert0 libvisual-0.4-0
  libvo-aacenc0 libvo-amrwbenc0 libwavpack1 libwebpdemux2
  libwebrtc-audio-processing1 libwildmidi2 libwoff1 libxcomposite1 libxdamage1
  libxfont2 libxkbfile1 libxmuu1 libxslt1.1 libxtst6 libyuv0 libzbar0
  libzxingcore1 session-migration systemd systemd-sysv timgm6mb-soundfont
  ubuntu-mono x11-xkb-utils xauth xfonts-cyrillic xfonts-encodings
  xfonts-scalable xfonts-utils xserver-common xvfb
The following packages will be upgraded:
  gcc-12-base libasound2 libasound2-data libatomic1 libcairo-gobject2
  libcairo2 libcc1-0 libcups2 libelf1 libfreetype6 libgbm1 libgcc-s1
  libgdk-pixbuf-2.0-0 libgdk-pixbuf2.0-common libgfortran5 libgl1-mesa-dri
  libglapi-mesa libglib2.0-0 libglx-mesa0 libgomp1 libharfbuzz0b libitm1
  liblcms2-2 liblsan0 libnspr4 libnss3 libopenjp2-7 libpng16-16 libquadmath0
  libstdc++6 libsystemd0 libubsan1 libxml2
33 upgraded, 155 newly installed, 0 to remove and 134 not upgraded.
Need to get 95.3 MB of archives.
After this operation, 242 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libsystemd0 amd64 249.11-0ubuntu3.22 [316 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 libargon2-1 amd64 0~20171227-0.3 [19.5 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libdevmapper1.02.1 amd64 2:1.02.175-2.1ubuntu5 [139 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libjson-c5 amd64 0.15-3~ubuntu1.22.04.2 [33.5 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libcryptsetup12 amd64 2:2.4.3-1ubuntu1.3 [211 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libip4tc2 amd64 1.8.7-1ubuntu5.2 [19.9 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libkmod2 amd64 29-1ubuntu1.1 [48.1 kB]
Get:8 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 systemd amd64 249.11-0ubuntu3.22 [4,587 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 systemd-sysv amd64 249.11-0ubuntu3.22 [10.5 kB]
Get:10 http://archive.ubuntu.com/ubuntu jammy/universe amd64 fonts-ipafont-gothic all 00303-21ubuntu1 [3,513 kB]
Get:11 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libatomic1 amd64 12.3.0-1ubuntu1~22.04.3 [10.5 kB]
Get:12 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libubsan1 amd64 12.3.0-1ubuntu1~22.04.3 [976 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 gcc-12-base amd64 12.3.0-1ubuntu1~22.04.3 [216 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libstdc++6 amd64 12.3.0-1ubuntu1~22.04.3 [699 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libquadmath0 amd64 12.3.0-1ubuntu1~22.04.3 [154 kB]
Get:16 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 liblsan0 amd64 12.3.0-1ubuntu1~22.04.3 [1,069 kB]
Get:17 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libitm1 amd64 12.3.0-1ubuntu1~22.04.3 [30.2 kB]
Get:18 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgomp1 amd64 12.3.0-1ubuntu1~22.04.3 [127 kB]
Get:19 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgfortran5 amd64 12.3.0-1ubuntu1~22.04.3 [879 kB]
Get:20 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libcc1-0 amd64 12.3.0-1ubuntu1~22.04.3 [48.3 kB]
Get:21 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgcc-s1 amd64 12.3.0-1ubuntu1~22.04.3 [53.9 kB]
Get:22 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 dbus amd64 1.12.20-2ubuntu4.1 [158 kB]
Get:23 http://archive.ubuntu.com/ubuntu jammy/main amd64 iso-codes all 4.9.0-1 [3,459 kB]
Get:24 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libcap2-bin amd64 1:2.44-1ubuntu0.22.04.3 [26.0 kB]
Get:25 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libelf1 amd64 0.186-1ubuntu0.1 [51.1 kB]
Get:26 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libglib2.0-0 amd64 2.72.4-0ubuntu2.9 [1,467 kB]
Get:27 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libpam-systemd amd64 249.11-0ubuntu3.22 [203 kB]
Get:28 http://archive.ubuntu.com/ubuntu jammy/main amd64 libtext-iconv-perl amd64 1.7-7build3 [14.3 kB]
Get:29 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libxml2 amd64 2.9.13+dfsg-1ubuntu0.12 [765 kB]
Get:30 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libpng16-16 amd64 1.6.37-3ubuntu0.6 [192 kB]
Get:31 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxmuu1 amd64 2:1.1.3-3 [10.2 kB]
Get:32 http://archive.ubuntu.com/ubuntu jammy/main amd64 xauth amd64 1:1.1-1build2 [27.5 kB]
Get:33 http://archive.ubuntu.com/ubuntu jammy/main amd64 hicolor-icon-theme all 0.17-2 [9,976 B]
Get:34 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgdk-pixbuf2.0-common all 2.42.8+dfsg-1ubuntu0.5 [5,560 B]
Get:35 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgdk-pixbuf-2.0-0 amd64 2.42.8+dfsg-1ubuntu0.5 [148 kB]
Get:36 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 gtk-update-icon-cache amd64 3.24.33-1ubuntu2.2 [31.4 kB]
Get:37 http://archive.ubuntu.com/ubuntu jammy/main amd64 humanity-icon-theme all 0.6.16 [1,282 kB]
Get:38 http://archive.ubuntu.com/ubuntu jammy/main amd64 ubuntu-mono all 20.10-0ubuntu2 [153 kB]
Get:39 http://archive.ubuntu.com/ubuntu jammy/main amd64 adwaita-icon-theme all 41.0-1ubuntu1 [3,444 kB]
Get:40 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 dbus-user-session amd64 1.12.20-2ubuntu4.1 [9,442 B]
Get:41 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libdconf1 amd64 0.40.0-3ubuntu0.1 [40.5 kB]
Get:42 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 dconf-service amd64 0.40.0-3ubuntu0.1 [28.1 kB]
Get:43 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 dconf-gsettings-backend amd64 0.40.0-3ubuntu0.1 [22.7 kB]
Get:44 http://archive.ubuntu.com/ubuntu jammy/main amd64 emacsen-common all 3.0.4 [14.9 kB]
Get:45 http://archive.ubuntu.com/ubuntu jammy/main amd64 dictionaries-common all 1.28.14 [185 kB]
Get:46 http://archive.ubuntu.com/ubuntu jammy/main amd64 fonts-freefont-ttf all 20120503-10build1 [2,388 kB]
Get:47 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 fonts-noto-color-emoji all 2.047-0ubuntu0.22.04.1 [10.0 MB]
Get:48 http://archive.ubuntu.com/ubuntu jammy/universe amd64 fonts-tlwg-loma-otf all 1:0.7.3-1 [107 kB]
Get:49 http://archive.ubuntu.com/ubuntu jammy/universe amd64 fonts-unifont all 1:14.0.01-1 [3,551 kB]
Get:50 http://archive.ubuntu.com/ubuntu jammy/universe amd64 fonts-wqy-zenhei all 0.9.45-8 [7,472 kB]
Get:51 http://archive.ubuntu.com/ubuntu jammy/main amd64 libproxy1v5 amd64 0.4.17-2 [51.9 kB]
Get:52 http://archive.ubuntu.com/ubuntu jammy/main amd64 glib-networking-common all 2.72.0-1 [3,718 B]
Get:53 http://archive.ubuntu.com/ubuntu jammy/main amd64 glib-networking-services amd64 2.72.0-1 [9,982 B]
Get:54 http://archive.ubuntu.com/ubuntu jammy/main amd64 session-migration amd64 0.3.6 [9,774 B]
Get:55 http://archive.ubuntu.com/ubuntu jammy/main amd64 gsettings-desktop-schemas all 42.0-1ubuntu1 [31.1 kB]
Get:56 http://archive.ubuntu.com/ubuntu jammy/main amd64 glib-networking amd64 2.72.0-1 [69.8 kB]
Get:57 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libdw1 amd64 0.186-1ubuntu0.1 [251 kB]
Get:58 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libunwind8 amd64 1.3.2-2build2.1 [54.5 kB]
Get:59 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgstreamer1.0-0 amd64 1.20.3-0ubuntu1.1 [984 kB]
Get:60 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 liborc-0.4-0 amd64 1:0.4.32-2ubuntu0.1 [228 kB]
Get:61 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgstreamer-plugins-base1.0-0 amd64 1.20.1-1ubuntu0.6 [848 kB]
Get:62 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 gstreamer1.0-libav amd64 1.20.3-0ubuntu1 [103 kB]
Get:63 http://archive.ubuntu.com/ubuntu jammy/main amd64 libcdparanoia0 amd64 3.10.2+debian-14build2 [49.3 kB]
Get:64 http://archive.ubuntu.com/ubuntu jammy/main amd64 libvisual-0.4-0 amd64 0.4.0-17build2 [108 kB]
Get:65 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 gstreamer1.0-plugins-base amd64 1.20.1-1ubuntu0.6 [712 kB]
Get:66 http://archive.ubuntu.com/ubuntu jammy/main amd64 libgpm2 amd64 1.20.7-10build1 [15.3 kB]
Get:67 http://archive.ubuntu.com/ubuntu jammy/main amd64 libaa1 amd64 1.4p5-50build1 [51.9 kB]
Get:68 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libfreetype6 amd64 2.11.1+dfsg-1ubuntu0.3 [388 kB]
Get:69 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libcairo-gobject2 amd64 1.16.0-5ubuntu2.1 [19.5 kB]
Get:70 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libcairo2 amd64 1.16.0-5ubuntu2.1 [628 kB]
Get:71 http://archive.ubuntu.com/ubuntu jammy/main amd64 libdv4 amd64 1.0.0-14build1 [61.9 kB]
Get:72 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgstreamer-plugins-good1.0-0 amd64 1.20.3-0ubuntu1.7 [30.6 kB]
Get:73 http://archive.ubuntu.com/ubuntu jammy/main amd64 libgudev-1.0-0 amd64 1:237-2build1 [16.3 kB]
Get:74 http://archive.ubuntu.com/ubuntu jammy/main amd64 libshout3 amd64 2.4.5-1build3 [54.5 kB]
Get:75 http://archive.ubuntu.com/ubuntu jammy/main amd64 libtag1v5-vanilla amd64 1.11.1+dfsg.1-3ubuntu3 [304 kB]
Get:76 http://archive.ubuntu.com/ubuntu jammy/main amd64 libtag1v5 amd64 1.11.1+dfsg.1-3ubuntu3 [11.5 kB]
Get:77 http://archive.ubuntu.com/ubuntu jammy/main amd64 libv4lconvert0 amd64 1.22.1-2build1 [82.4 kB]
Get:78 http://archive.ubuntu.com/ubuntu jammy/main amd64 libv4l-0 amd64 1.22.1-2build1 [44.9 kB]
Get:79 http://archive.ubuntu.com/ubuntu jammy/main amd64 libwavpack1 amd64 5.4.0-1build2 [83.7 kB]
Get:80 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxdamage1 amd64 1:1.1.5-2build2 [7,154 B]
Get:81 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libsoup2.4-common all 2.74.2-3ubuntu0.7 [4,898 B]
Get:82 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libsoup2.4-1 amd64 2.74.2-3ubuntu0.7 [288 kB]
Get:83 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 gstreamer1.0-plugins-good amd64 1.20.3-0ubuntu1.7 [2,006 kB]
Get:84 http://archive.ubuntu.com/ubuntu jammy/main amd64 hunspell-en-us all 1:2020.12.07-2 [280 kB]
Get:85 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libabsl20210324 amd64 0~20210324.2-2ubuntu0.3 [386 kB]
Get:86 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libasound2 amd64 1.2.6.1-1ubuntu1.2 [391 kB]
Get:87 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libasound2-data all 1.2.6.1-1ubuntu1.2 [19.3 kB]
Get:88 http://archive.ubuntu.com/ubuntu jammy/main amd64 libaspell15 amd64 0.60.8-4build1 [325 kB]
Get:89 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk1.0-data all 2.36.0-3build1 [2,824 B]
Get:90 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk1.0-0 amd64 2.36.0-3build1 [51.9 kB]

In [6]:
from pyspark.sql import SparkSession

# 스파크 세션 생성
spark = (
    SparkSession.builder.appName("MelonChartAnalysis")
    .master("local[*]")
    .config("spark.sql.adaptive.enabled", "true")
    .getOrCreate()
)

In [22]:
import asyncio
from playwright.async_api import async_playwright
import pandas as pd

async def get_melon_chart_with_likes():
    async with async_playwright() as p:
        # 헤드리스 브라우저 실행
        browser = await p.chromium.launch(headless=True)
        page = await browser.new_page(user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36")
        
        print("멜론 차트 페이지 접속 중...")
        await page.goto("https://www.melon.com/chart/index.htm")
        
        # 좋아요 등 자바스크립트 데이터가 렌더링될 때까지 충분히 대기
        await page.wait_for_selector("tbody > tr", timeout=10000)
        await asyncio.sleep(2) 
        
        rank_list, title_list, artist_list, album_list, like_list = [], [], [], [], []
        
        # 페이지 내의 행(tr)들 가져오기
        rows = await page.locator("tbody > tr").all()
        
        for idx, item in enumerate(rows):
            try:
                # 1. 순위
                rank_elem = item.locator("span.rank")
                rank = await rank_elem.inner_text() if await rank_elem.count() > 0 else str(idx + 1)
                
                # 2. 제목 (.first 추가로 중복 방지)
                title_elem = item.locator("div.rank01 a").first
                title = await title_elem.inner_text() if await title_elem.count() > 0 else ""
                
                # 3. 가수 (.first 추가로 중복 방지)
                artist_elem = item.locator("div.rank02 a").first
                artist = await artist_elem.inner_text() if await artist_elem.count() > 0 else ""
                
                # 4. 앨범명 (.first 추가로 중복 방지)
                album_elem = item.locator("div.rank03 a").first
                album = await album_elem.inner_text() if await album_elem.count() > 0 else ""
                
                # 5. 좋아요 수
                like_count = 0
                like_elem = item.locator("button.like span.cnt")
                if await like_elem.count() > 0:
                    raw_text = await like_elem.inner_text()
                    clean_text = raw_text.replace("총건수", "").replace(",", "").strip()
                    if clean_text.isdigit():
                        like_count = int(clean_text)
                
                rank_list.append(int(rank.strip()))
                title_list.append(title.strip())
                artist_list.append(artist.strip())
                album_list.append(album.strip())
                like_list.append(like_count)
                
            except Exception as e:
                print(f"[{idx+1}번째 행 파싱 에러 발생]: {e}")
                continue

        print("수집된 데이터 개수:", len(rank_list))
                
        await browser.close()
        
        # 판다스 및 스파크 DF 변환
        pd_df = pd.DataFrame({
            "rank": rank_list,
            "title": title_list,
            "artist": artist_list,
            "album_name": album_list,
            "likes": like_list
        })

        print(pd_df)
        
        return spark.createDataFrame(pd_df)

# 코딩 환경에 맞춰 실행 (주피터 노트북인 경우 await 사용 가능)
df_melon_likes = await get_melon_chart_with_likes()

# 파켓 저장
df_melon_likes.write.mode("overwrite").parquet("./melon_firepower_data.parquet")
print("아이브 화력 분석용 데이터 수집 완료!")
df_melon_likes.filter(df_melon_likes["artist"].contains("아이브")).show(truncate=False)

멜론 차트 페이지 접속 중...
수집된 데이터 개수: 100
    rank        title         artist                           album_name  \
0      1        BiiiG   BIGBANG (빅뱅)                                BiiiG
1      2  LOVE ATTACK  RESCENE (리센느)                           SCENEDROME
2      3          갑자기  아이오아이 (I.O.I)  I.O.I 3rd MINI ALBUM [I.O.I : LOOP]
3      4       REDRED  CORTIS (코르티스)                           GREENGREEN
4      5  Pretty Girl  RESCENE (리센느)         Pretty Girl - Special Single
..   ...          ...            ...                                  ...
95    96    OVERDRIVE      TWS (투어스)                            play hard
96    97     우리들의 블루스            임영웅                              IM HERO
97    98    BLACKHOLE      IVE (아이브)                              REVIVE+
98    99     Hooligan          방탄소년단                              ARIRANG
99   100          2.0          방탄소년단                              ARIRANG

     likes
0    29550
1   138039
2    74833
3    84802
4    54168
..     ...
95   46977
96  126300
97   41804
98   33772
99   31928

[100 rows x 5 columns]
아이브 화력 분석용 데이터 수집 완료!
+----+-----------+------------+-----------+------+
|rank|title      |artist      |album_name |likes |
+----+-----------+------------+-----------+------+
|29  |BANG BANG  |IVE (아이브)|REVIVE+    |67953 |
|71  |REBEL HEART|IVE (아이브)|IVE EMPATHY|122173|
|89  |I AM       |IVE (아이브)|I've IVE   |239527|
|98  |BLACKHOLE  |IVE (아이브)|REVIVE+    |41804 |
+----+-----------+------------+-----------+------+

In [23]:
df_melon_likes.show()

+----+-------------------------+----------------------+--------------------+------+
|rank|                    title|                artist|          album_name| likes|
+----+-------------------------+----------------------+--------------------+------+
|   1|                    BiiiG|        BIGBANG (빅뱅)|               BiiiG| 29550|
|   2|              LOVE ATTACK|      RESCENE (리센느)|          SCENEDROME|138039|
|   3|                   갑자기|    아이오아이 (I.O.I)|I.O.I 3rd MINI AL...| 74833|
|   4|                   REDRED|     CORTIS (코르티스)|          GREENGREEN| 84802|
|   5|              Pretty Girl|      RESCENE (리센느)|Pretty Girl - Spe...| 54168|
|   6|                 LEMONADE|                 aespa|LEMONADE - The 2n...| 55222|
|   7|                  Deja Vu|      RESCENE (리센느)|             Dearest| 45382|
|   8|                  It′s Me|         아일릿(ILLIT)|    MAMIHLAPINATAPAI| 55496|
|   9|                   만찬가|        태연 (TAEYEON)|  J-POP REMAKE Vol.1| 38859|
|  10|                      BAD|       ATEEZ(에이티즈)|GOLDEN HOUR : Part.5| 22063|
|  11|            여름아 부탁해|          볼빨간사춘기|       여름아 부탁해| 19664|
|  12|                 Drowning|                 WOODZ|               OO-LI|306889|
|  13|                캐치 캐치|         YENA (최예나)|        LOVE CATCHER| 48885|
|  14|                    RUDE!|Hearts2Hearts (하츠...|               RUDE!| 72784|
|  15|         사랑하게 될 거야|                한로로|            이상비행|146465|
|  16|             Good Goodbye|          화사 (HWASA)|        Good Goodbye|123920|
|  17|              소문의 낙원|           AKMU (악뮤)|                개화| 89011|
|  18|               Lemon Tang|Hearts2Hearts (하츠...|Lemon Tang - The ...| 29328|
|  19|                      0+0|                한로로|        자몽살구클럽|121699|
|  20|기쁨, 슬픔, 아름다운 마음|           AKMU (악뮤)|                개화| 90621|
+----+-------------------------+----------------------+--------------------+------+
only showing top 20 rows